const CONFIG={budget:500,limits:{P:3,D:8,C:8,A:6}};let players=[];let selected=null;let role='ALL';let state=JSON.parse(localStorage.getItem('fantaAIState')||'null')||{credits:500,roster:{P:[],D:[],C:[],A:[]}};
const $=id=>document.getElementById(id);const money=n=>Math.round(Number(n)||0);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){try{const r=await fetch('data/players.json',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);players=await r.json();if(!Array.isArray(players))throw Error('JSON non valido');}catch(e){$('players').innerHTML=`<div class="empty error">Errore caricamento database: ${esc(e.message)}</div>`;return}$('playerCount').textContent=players.length;bind();render()}
function bind(){$('search').addEventListener('input',render);document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{role=b.dataset.role;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}));$('analyzeBtn').addEventListener('click',analyze);$('resetBtn').addEventListener('click',()=>{if(confirm('Vuoi azzerare crediti e rosa?')){state={credits:500,roster:{P:[],D:[],C:[],A:[]}};save();render()}})}
function render(){const q=$('search').value.trim().toLowerCase();const list=players.filter(p=>(role==='ALL'||p.role===role)&&(!q||`${p.name} ${p.team}`.toLowerCase().includes(q)));$('players').innerHTML=list.map(p=>`<div class="player" data-id="${esc(p.name)}"><div class="role">${esc(p.role)}</div><div><strong>${esc(p.name)}</strong><span>${esc(p.team)}</span></div><div class="price">${money(p.quotation??p.price)}</div></div>`).join('')||'<div class="empty">Nessun giocatore trovato.</div>';document.querySelectorAll('.player').forEach(el=>el.addEventListener('click',()=>select(players.find(p=>p.name===el.dataset.id))));updateHeader();renderRoster()}
function select(p){selected=p;$('auctionPlayer').value=p.name;$('auctionPrice').value=money(p.quotation??p.price);const q=money(p.quotation??p.price);const fvm=money(p.fvm);const expected=Math.max(q,Math.round((fvm||q*10)/10));const alternatives=players.filter(x=>x.role===p.role&&x.name!==p.name).sort((a,b)=>score(b)-score(a)).slice(0,4);$('details').innerHTML=`<div class="detail-top"><div><div class="detail-name">${esc(p.name)}</div><p class="muted">${esc(p.team)} · ruolo ${esc(p.role)}</p></div><div class="detail-price">${q}<small>quotazione</small></div></div><div class="chips"><span class="chip">FVM ${fvm||'-'}</span><span class="chip">Prezzo base ${q}</span><span class="chip">Stima strategica ${expected}</span></div><div class="metrics"><div class="metric"><small>MEDIA</small><b>${p.media??'-'}</b></div><div class="metric"><small>FANTAMEDIA</small><b>${p.fantamedia??'-'}</b></div><div class="metric"><small>GOL</small><b>${p.gol??'-'}</b></div></div><div class="plan"><h3>Alternative</h3>${alternatives.map(x=>`<div class="plan-item"><span>${esc(x.name)}</span><b>${money(x.quotation??x.price)}</b></div>`).join('')||'<p class="muted">Nessuna alternativa disponibile.</p>'}</div>`;analyze()}
function score(p){return money(p.fvm)*.45+Number(p.fantamedia||0)*3+Number(p.media||0)*2+Number(p.presenze||0)*.15}
function analyze(){if(!selected){$('advice').className='advice empty';$('advice').textContent='Seleziona un giocatore per iniziare.';return}const current=money($('auctionPrice').value);const q=money(selected.quotation??selected.price)||1;const fvm=money(selected.fvm);let value=Math.max(q,Math.round((fvm||q*10)/10));let idealMin=Math.max(1,Math.round(value*.85));let idealMax=Math.max(idealMin+1,Math.round(value*1.15));let absolute=Math.max(idealMax,Math.round(value*1.35));const otherSlots=25-Object.values(state.roster).flat().length;absolute=Math.min(absolute,Math.max(1,state.credits-Math.max(0,otherSlots-1)));const decision=current<=idealMax?'CONTINUA':current<=absolute?'ATTENZIONE':'FERMATI';const cls=decision==='CONTINUA'?'good':decision==='ATTENZIONE'?'warn':'bad';const alts=players.filter(x=>x.role===selected.role&&x.name!==selected.name).sort((a,b)=>score(b)-score(a)).slice(0,3);$('advice').className=`advice ${cls}`;$('advice').innerHTML=`<div class="decision">${decision}</div><div class="rows"><div><small>PREZZO ATTUALE</small><b>${current}</b></div><div><small>PREZZO IDEALE</small><b>${idealMin}–${idealMax}</b></div><div><small>MASSIMO PERSONALE</small><b>${absolute}</b></div></div><div class="plan"><h3>Piano B</h3>${alts.map(x=>`<div class="plan-item"><span>${esc(x.name)}</span><b>max ${Math.min(absolute,money(x.quotation??x.price)*2)}</b></div>`).join('')}</div>`;$('status').textContent=decision}
function updateHeader(){const count=Object.values(state.roster).flat().length;$('credits').textContent=state.credits;$('creditsTop').textContent=state.credits;$('rosterCount').textContent=`${count}/25`}
function renderRoster(){$('roster').innerHTML=['P','D','C','A'].map(r=>`<div class="roster-col"><h3>${r} ${state.roster[r].length}/${CONFIG.limits[r]}</h3>${state.roster[r].map(p=>`<div class="roster-player"><span>${esc(p.name)}</span><b>${p.price}</b></div>`).join('')||'<span class="muted">Vuoto</span>'}</div>`).join('')}
function save(){localStorage.setItem('fantaAIState',JSON.stringify(state))}init();
