const C={budget:500,limits:{P:3,D:8,C:8,A:6},split:{P:.07,D:.19,C:.32,A:.42}};
let players=[],sel=null,role='ALL';
let state=JSON.parse(localStorage.getItem('fantabbaState')||'null')||{credits:500,roster:{P:[],D:[],C:[],A:[]},logs:[],opponents:[]};
const $=id=>document.getElementById(id),N=v=>Math.round(Number(v)||0),S=v=>Number(v)||0,save=()=>localStorage.setItem('fantabbaState',JSON.stringify(state));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const roles=Object.keys(C.limits);const q=p=>N(p.quotation??p.price),fvm=p=>N(p.fvm),myNames=()=>Object.values(state.roster).flat().map(x=>x.name.toLowerCase());
const sold=name=>state.logs.some(x=>!x.mine&&x.player?.toLowerCase()===name.toLowerCase());
const need=r=>Math.max(0,C.limits[r]-state.roster[r].length);
function marketAvg(p){if(N(p.auctionAvg)>0)return N(p.auctionAvg);if(N(p.averageAuction)>0)return N(p.averageAuction);const x=state.logs.filter(l=>l.player?.toLowerCase()===p.name.toLowerCase()&&!l.mine);return x.length?Math.round(x.reduce((a,b)=>a+N(b.price),0)/x.length):0}
function dataQuality(p){return marketAvg(p)?(p.auctionSeason||'2026/27'):'N/D'}
function expected(p){const fm=S(p.fantamedia),mv=S(p.media),apps=S(p.presenze),g=S(p.gol??p.goals),a=S(p.assist??p.assists),start=S(p.titolarita??p.starter);let x=fm*6+mv*2+Math.min(apps,38)*.12+g*1.8+a*1.2+start*.04;if(S(p.fixtureScore))x+=S(p.fixtureScore)*1.5;return x}
function valueScore(p){const price=marketAvg(p)||Math.max(q(p),Math.round(fvm(p)/10)||q(p));return expected(p)/Math.max(price,1)}
function basePrice(p){return marketAvg(p)||Math.max(q(p),Math.round(fvm(p)/10)||q(p))}
function reserve(){let r=0;roles.forEach(x=>r+=need(x));return Math.max(0,r)}
function dynamicMax(p){if(!p||need(p.role)<=0||sold(p.name)||myNames().includes(p.name.toLowerCase()))return 0;const base=basePrice(p);if(!base)return 0;const peers=players.filter(x=>x.role===p.role&&!sold(x.name)&&!myNames().includes(x.name.toLowerCase())).sort((a,b)=>valueScore(b)-valueScore(a));const rank=Math.max(0,peers.findIndex(x=>x.name===p.name));const premium=rank<3?1.10:rank<8?1.04:0.98;const fit=1+Math.min(.08,Math.max(-.08,(expected(p)-medianRole(p.role))/Math.max(medianRole(p.role),1)*.05));const cap=Math.max(1,state.credits-reserve());return Math.min(cap,Math.max(1,Math.round(base*premium*fit)))}
function medianRole(r){const a=players.filter(p=>p.role===r).map(expected).filter(Boolean).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:1}
function decision(p,current){const m=dynamicMax(p),avg=marketAvg(p),soft=Math.round((avg||basePrice(p))*1.03),hard=m;let d=current<=soft?'CONTINUA':current<=hard?'ATTENZIONE':'FERMATI';if(current>state.credits-reserve()||need(p.role)<=0||sold(p.name)||myNames().includes(p.name.toLowerCase()))d='FERMATI';return{d,m,avg,soft,quality:dataQuality(p)}}
async function init(){try{const r=await fetch('data/players.json?ts='+Date.now());const x=await r.json();if(Array.isArray(x))players=x}catch(e){players=[]}const imp=localStorage.getItem('fantabbaImported');if(imp)try{const x=JSON.parse(imp);if(Array.isArray(x)&&x.length)players=x}catch{}$('playerCount').textContent=players.length;$('dataBadge').textContent=players.length?'DATABASE':'NO DATABASE';bind();renderAll()}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{role=b.dataset.role;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.role===role));renderPlayers()});['searchAuction','searchPlayers'].forEach(id=>$(id)?.addEventListener('input',renderPlayers));$('auctionPrice').oninput=analyze;$('analyzeBtn').onclick=analyze;$('addLog').onclick=addLog;$('saveOpp').onclick=saveOpp;$('resetBtn').onclick=reset;$('buildBtn').onclick=build;$('importBtn').onclick=importData}
function tab(t){['auction','builder','players','strategy','tools'].forEach(x=>$('tab-'+x)?.classList.toggle('hidden',x!==t));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));if(t==='strategy')strategy()}
function list(){const qx=(($('searchAuction')?.value||'')+' '+($('searchPlayers')?.value||'')).trim().toLowerCase();return players.filter(p=>(role==='ALL'||p.role===role)&&(!qx||`${p.name} ${p.team}`.toLowerCase().includes(qx)))}
function renderPlayers(){const html=list().map(p=>`<div class="player" data-name="${esc(p.name)}"><div class="role">${esc(p.role)}</div><div><strong>${esc(p.name)}</strong><span>${esc(p.team)}${sold(p.name)||myNames().includes(p.name.toLowerCase())?' · ASSEGNATO':''}</span></div><div class="price">${q(p)}</div></div>`).join('')||'<div class="empty">Nessun giocatore trovato.</div>';['playersAuction','playersList'].forEach(id=>{if($(id))$(id).innerHTML=html});document.querySelectorAll('.player').forEach(e=>e.onclick=()=>select(players.find(p=>p.name===e.dataset.name)))}
function alternatives(p){return players.filter(x=>x.role===p.role&&x.name!==p.name&&!sold(x.name)&&!myNames().includes(x.name.toLowerCase())).sort((a,b)=>valueScore(b)-valueScore(a)).slice(0,5)}
function select(p){if(!p)return;sel=p;$('auctionPlayer').value=p.name;$('auctionPrice').value=q(p)||marketAvg(p)||1;const alts=alternatives(p);$('details').innerHTML=`<div class="detail-top"><div><div class="detail-name">${esc(p.name)}</div><p>${esc(p.team)} · ${p.role}</p></div><div class="detail-price">${q(p)}<small>QUOTAZIONE</small></div></div><div class="chips"><span class="chip">FVM ${fvm(p)||'n/d'}</span><span class="chip">MEDIA ASTA 8×500 ${marketAvg(p)||'n/d'}</span><span class="chip">DATO ${esc(dataQuality(p))}</span><span class="chip">SLOT ${need(p.role)}</span></div><div class="metrics"><div class="metric"><small>FANTAMEDIA</small><b>${p.fantamedia??'n/d'}</b></div><div class="metric"><small>MEDIA VOTO</small><b>${p.media??'n/d'}</b></div><div class="metric"><small>ATTESO</small><b>${expected(p).toFixed(1)}</b></div></div><div class="plan"><h3>PIANO B</h3>${alts.map(x=>`<div class="plan-item"><span>${esc(x.name)} · ${esc(x.team)}</span><b>max ${dynamicMax(x)}</b></div>`).join('')||'<p>Dati insufficienti.</p>'}</div><button class="primary" id="buy" style="width:100%;margin-top:14px">ACQUISTA PER ME</button>`;$('buy').onclick=buy;analyze()}
function analyze(){if(!sel)return;const cur=N($('auctionPrice').value),d=decision(sel,cur),cls=d.d==='CONTINUA'?'good':d.d==='ATTENZIONE'?'warn':'bad',alts=alternatives(sel).slice(0,3);$('advice').className='advice '+cls;$('advice').innerHTML=`<div class="decision">${d.d}</div><p>${d.d==='CONTINUA'?'Prezzo ancora coerente con il mercato e con il tuo piano.':d.d==='ATTENZIONE'?'Puoi rilanciare, ma sei vicino al limite: non inseguire.':'Il prezzo ha superato il limite strategico: passa al Piano B.'}</p><div class="rows"><div><small>ATTUALE</small><b>${cur}</b></div><div><small>MEDIA REALE</small><b>${d.avg||'N/D'}</b></div><div><small>MASSIMO TUO</small><b>${d.m}</b></div></div><div class="plan"><h3>SE LO PERDI</h3>${alts.map(x=>`<div class="plan-item"><span>${esc(x.name)}</span><b>max ${dynamicMax(x)}</b></div>`).join('')}</div>`;$('status').textContent=d.d;$('aiSummary').innerHTML=`<b>${esc(sel.name)}</b>: media 8×500 <b>${d.avg||'non disponibile'}</b>, dato <b>${esc(d.quality)}</b>, massimo personale <b>${d.m}</b>. A <b>${cur}</b>: <b>${d.d}</b>. ${d.d==='FERMATI'?'Il sistema conserva le alternative per non farti inseguire il prezzo.':'Il limite considera anche crediti e slot ancora necessari.'}`}
function buy(){const p=N($('auctionPrice').value);if(!sel||p<1||p>state.credits||need(sel.role)<=0)return alert('Prezzo, crediti o slot non validi.');state.roster[sel.role].push({name:sel.name,team:sel.team,price:p});state.credits-=p;state.logs.push({player:sel.name,team:'MIA',price:p,mine:true,date:Date.now()});save();renderAll();$('status').textContent='ACQUISTATO'}
function addLog(){const player=$('logPlayer').value.trim(),team=$('logTeam').value.trim(),price=N($('logPrice').value);if(!player||!price)return;state.logs.push({player,team,price,mine:false,date:Date.now()});save();$('logPlayer').value='';$('logTeam').value='';$('logPrice').value='';renderAll()}
function logRender(){$('auctionLog').innerHTML=state.logs.slice(-30).reverse().map(x=>`<div class="plan-item"><span>${esc(x.player)} · ${esc(x.mine?'MIA':x.team||'avversario')}</span><b>${x.price}</b></div>`).join('')||'<p>Nessun prezzo registrato.</p>'}
function saveOpp(){const name=$('oppName').value.trim(),credits=N($('oppCredits').value);if(!name)return;const x=state.opponents.find(a=>a.name.toLowerCase()===name.toLowerCase());x?x.credits=credits:state.opponents.push({name,credits});save();$('oppName').value='';$('oppCredits').value='';strategy()}
function strategy(){if(!$('budgetPlan'))return;const remaining=state.credits;const rows=roles.map(r=>{const target=Math.round(C.budget*C.split[r]);return`<div class="budget-row"><span><b>${r}</b> · ${need(r)} slot rimasti</span><strong>${Math.min(remaining,Math.max(0,target))} cr base</strong></div>`}).join('');$('budgetPlan').innerHTML=rows+'<p style="margin-top:12px;color:#7e8795">Il 7/19/32/42% è un punto di partenza statistico, non una regola: FantAbba lo ricalcola in base alla rosa.</p>';$('targets').innerHTML=players.filter(p=>!sold(p.name)&&!myNames().includes(p.name.toLowerCase())).sort((a,b)=>valueScore(b)-valueScore(a)).slice(0,25).map(p=>`<div class="plan-item"><span>${esc(p.name)} · ${p.role} · ${esc(p.team)}</span><b>max ${dynamicMax(p)}</b></div>`).join('');$('opponents').innerHTML=state.opponents.map(x=>`<div class="plan-item"><span>${esc(x.name)}</span><b>${x.credits} cr</b></div>`).join('')||'<p>Nessun avversario.</p>'}
function priceForBuild(p){const avg=marketAvg(p);return avg>0?avg:Math.max(q(p),Math.round(fvm(p)/10)||q(p))}
function build(){const style=$('buildStyle')?.value||'balanced',budget=N($('buildBudget')?.value)||500;let remaining=budget,roster={P:[],D:[],C:[],A:[]};const pool={};roles.forEach(r=>pool[r]=players.filter(p=>p.role===r&&!sold(p.name)&&!myNames().includes(p.name.toLowerCase())).sort((a,b)=>valueScore(b)-valueScore(a)));const desirability=p=>{let v=valueScore(p);if(style==='value')v*=1.08;if(style==='stars'&&p.role==='A')v*=1.18;if(style==='stars'&&p.role==='C')v*=1.05;if(style==='safe')v*=1-(p.riskScore?Math.min(.15,p.riskScore/100):0);return v};roles.forEach(r=>pool[r].sort((a,b)=>desirability(b)-desirability(a)));const allSlots=roles.reduce((s,r)=>s+C.limits[r],0);const minUnit=1;let slotsRemaining=allSlots;const chooseBest=r=>{const candidates=pool[r].filter(p=>priceForBuild(p)<=remaining-(slotsRemaining-1)*minUnit);return candidates[0]||null};while(slotsRemaining>0){let best=null,bestR=null,bestScore=-Infinity;for(const r of roles){if(roster[r].length>=C.limits[r])continue;const p=chooseBest(r);if(!p)continue;const cost=priceForBuild(p),score=desirability(p)/(cost||1);if(score>bestScore){best=p;bestR=r;bestScore=score}}if(!best)break;const cost=priceForBuild(best);roster[bestR].push({p:best,c:cost,real:marketAvg(best)>0});remaining-=cost;slotsRemaining--}let total=budget-remaining,html=`<div class="build-total"><b>ROSA REALIZZABILE</b><strong>${total} / ${budget} crediti</strong></div><div class="build-grid">`;roles.forEach(r=>{html+=`<div class="build-card"><h3>${r} ${roster[r].length}/${C.limits[r]}</h3>${roster[r].map(x=>`<div class="plan-item"><span>${esc(x.p.name)} <small>${x.real?'MEDIA 8×500':'STIMA'}</small></span><b>${x.c}</b></div>`).join('')||'<p>Dati insufficienti.</p>'}</div>`});html+='</div>';if(slotsRemaining>0)html+=`<div class="advice bad" style="margin-top:14px"><b>ROSA NON COMPLETA</b><p>Non esistono abbastanza prezzi compatibili con ${budget} crediti nel database attuale. Non invento prezzi per riempire gli slot.</p></div>`;else html+=`<div class="advice good" style="margin-top:14px"><b>25/25 SLOT COPERTI</b><p>Il costo totale è compatibile con il budget. MEDIA 8×500 indica una media reale disponibile; STIMA indica che la media reale non è presente.</p></div>`;$('builderResult').className='builder-result';$('builderResult').innerHTML=html}
function renderRoster(){$('roster').innerHTML=roles.map(r=>`<div class="roster-col"><h3>${r} ${state.roster[r].length}/${C.limits[r]}</h3>${state.roster[r].map(x=>`<div class="roster-player"><span>${esc(x.name)}</span><b>${x.price}</b></div>`).join('')||'<span>Vuoto</span>'}</div>`).join('')}
function update(){const count=Object.values(state.roster).flat().length;$('credits').textContent=state.credits;$('creditsTop').textContent=state.credits;$('rosterCount').textContent=`${count}/25`;$('playerCount').textContent=players.length}
function renderAll(){renderPlayers();logRender();renderRoster();strategy();update();if(sel&&players.some(p=>p.name===sel.name))analyze()}
function reset(){if(confirm('Azzerare rosa, crediti, prezzi registrati e avversari?')){state={credits:500,roster:{P:[],D:[],C:[],A:[]},logs:[],opponents:[]};save();renderAll()}}
function parseCSV(t){const ls=t.split(/\r?\n/).filter(Boolean),sep=ls[0].includes(';')?';':',',h=ls.shift().split(sep).map(x=>x.trim().replace(/^"|"$/g,''));return ls.map(l=>{const c=l.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));return Object.fromEntries(h.map((k,i)=>[k,c[i]||'']))})}
function normalize(rows){return rows.map(r=>{const k=Object.keys(r),get=a=>{const z=k.find(x=>a.some(y=>x.toLowerCase().includes(y)));return z?r[z]:''};const rr=String(get(['ruolo classic','ruolo','role'])).toUpperCase();const rr2=rr.startsWith('P')||rr.includes('PORT')?'P':rr.startsWith('D')||rr.includes('DIF')?'D':rr.startsWith('C')||rr.includes('CENT')?'C':rr.startsWith('A')||rr.includes('ATT')?'A':'';return{name:String(get(['calciatore','giocatore','nome','name'])).trim(),team:String(get(['squadra','team','club'])).trim(),role:rr2,quotation:N(get(['quotazione','quot','price'])),fvm:N(get(['fvm','fantavalore'])),auctionAvg:N(get(['asta 8','8x500','500','media asta','auctionavg']))}}).filter(x=>x.name&&x.role)}
function importData(){const f=$('fileInput').files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{let x;if(f.name.endsWith('.json'))x=JSON.parse(rd.result);else if(f.name.endsWith('.csv'))x=parseCSV(rd.result);else{const wb=XLSX.read(rd.result,{type:'array'});x=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]])}const n=normalize(x);if(n.length<50)throw Error('Pochi giocatori');players=n;localStorage.setItem('fantabbaImported',JSON.stringify(n));$('importStatus').textContent=`Importati ${n.length} giocatori.`;renderAll()}catch(e){$('importStatus').textContent='Import fallito: '+e.message}};if(f.name.endsWith('.xlsx'))rd.readAsArrayBuffer(f);else rd.readAsText(f)}
window.FantAbba={players,state,marketAvg,basePrice,valueScore,dynamicMax,build};
init();