(()=>{
'use strict';
const CFG={budget:500,slots:{P:3,D:8,C:8,A:6},names:{P:'Portieri',D:'Difensori',C:'Centrocampisti',A:'Attaccanti'},guide:{P:35,D:95,C:160,A:210}};
const PRICE={
'LAUTARO MARTINEZ':84,'MALEN DONYELL':80,'THURAM MARCUS':71,'GONCALO RAMOS':70,'HOJLUND RASMUS':70,'KOLO MUANI':66,'PAZ NICO':61,'KEAN MOISE':60,'MCTOMINAY SCOTT':54,'YILDIZ KENAN':52,
'DIMARCO FEDERICO':62,'CALHANOGLU HAKAN':52,'PULISIC CHRISTIAN':48,'DE BRUYNE KEVIN':47,'LEAO RAFAEL':46,'DYBALA PAULO':45,'ORSOLINI RICCARDO':44,'ZACCAGNI MATTIA':43,'BARELLA NICOLO':42,'DAVID JONATHAN':41,
'SVILAR MILE':31,'MAIGNAN MIKE':30,'CARNESECCHI MARCO':27,'DE GEA DAVID':25
};
const S={players:[],view:'war',strategy:'balanced',roster:[],spent:0,selected:null};
const $=s=>document.querySelector(s); const norm=s=>String(s??'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const role=p=>{let r=String(p.role||p.ruolo||p.position||'').toUpperCase();return ['P','D','C','A'].find(x=>r.startsWith(x))||''};
const name=p=>p.name||p.nome||p.player||p.fullName||'Sconosciuto'; const team=p=>p.team||p.squadra||p.club||'';
const quote=p=>Number(p.quotation??p.quotazione??p.q??p.fvm??0)||0;
function real(p){let x=Number(p.auctionAvg8x500??p.avg8x500??p.price8x500??p.asta8x500);if(Number.isFinite(x)&&x>0)return x;let k=norm(name(p));if(PRICE[k]!=null)return PRICE[k];let hit=Object.keys(PRICE).find(z=>k===z||k.startsWith(z+' ')||z.startsWith(k+' '));return hit?PRICE[hit]:null}
function ref(p){let x=real(p);if(x)return x;let q=quote(p),r=role(p);let m={P:1.65,D:1.65,C:1.75,A:1.9}[r]||1.6;let cap={P:32,D:55,C:78,A:125}[r]||60;return Math.max(1,Math.min(cap,Math.round(q*m)))}
function refSource(p){return real(p)!=null?'ASTA REALE / BENCHMARK':'STIMA CALIBRATA'}
function fvm(p){return Number(p.fvm??p.FVM??p.fantamedia??0)||0}
function quality(p){return fvm(p)*8+quote(p)*1.4+(real(p)!=null?15:0)}
function value(p){return quality(p)/(ref(p)||1)}
function tier(p){let q=quote(p),r=role(p);if(r==='P')return q>=12?'PREMIUM':q>=7?'TITOLARE':'VALUE';if(r==='A')return q>=25?'TOP':q>=15?'SEMITOP':q>=8?'VALUE':'SLOT';if(r==='C')return q>=22?'TOP':q>=13?'SEMITOP':q>=7?'VALUE':'SLOT';return q>=18?'PREMIUM':q>=10?'TITOLARE':q>=5?'VALUE':'SLOT'}
const pool=r=>S.players.filter(p=>role(p)===r); const remaining=()=>CFG.budget-S.spent; const freeSlots=()=>25-S.roster.length;
function reserveAfter(p){return Math.max(25-(S.roster.length+1),0)}
function currentRoleBudget(r){let spent=S.roster.filter(p=>role(p)===r).reduce((s,p)=>s+(p.paid||0),0);let slots=S.roster.filter(p=>role(p)===r).length;return {spent,slots,left:CFG.slots[r]-slots}}
function maxBid(p){let r=role(p),rb=currentRoleBudget(r),roleRoom=CFG.guide[r]-rb.spent;let reserve=reserveAfter(p),cash=remaining()-reserve;if(rb.left<=1)roleRoom=Math.max(roleRoom,Math.min(cash,ref(p)));let scarcity=rb.left<=2?1.08:1;let strategic=Math.min(ref(p)*1.12,Math.max(1,roleRoom+Math.min(12,roleRoom*.12)));return Math.max(1,Math.min(cash,Math.round(strategic*scarcity)))}
function decision(p,price){let lim=maxBid(p),m=ref(p),x=price;if(x>lim)return ['STOP','bad','Non inseguire: il costo-opportunità supera il valore e mette a rischio gli slot rimanenti.'];if(x>=lim*.95)return ['ULTIMO RILANCIO','warn','Questo è il tuo ultimo colpo. Se qualcuno rilancia ancora, passa al sostituto.'];if(x<=m*.82)return ['RILANCIA FORTE','good','Prezzo molto sotto il riferimento: è un punto in cui puoi aggredire il giocatore.'];if(x<=m)return ['RILANCIA','good','Prezzo dentro il range: continua, ma senza superare il limite.'];if(x<=m*1.08)return ['RILANCIA CON CAUTELA','warn','Stai pagando un premio. Fallo solo se è un target prioritario.'];return ['PASSA','bad','Il prezzo è già sopra il valore che FantAbba gli assegna.']}
function alternatives(p){let r=role(p),target=ref(p);return pool(r).filter(x=>x!==p&&!S.roster.includes(x)).sort((a,b)=>{let da=Math.abs(ref(a)-target),db=Math.abs(ref(b)-target);return da-db||value(b)-value(a)}).slice(0,3)}
function targetSet(r){let a=pool(r).filter(p=>ref(p)>0).sort((x,y)=>value(y)-value(x));if(r==='P')return keeperPlans(a);let wanted=r==='A'?[.95,.65,.38]:r==='C'?[.9,.62,.38]:[.85,.55,.3];let out=[];for(let w of wanted){let top=a.find(p=>!out.includes(p)&&ref(p)<=Math.max(5,CFG.guide[r]*w/(CFG.slots[r]/2)));if(top)out.push(top)}return out}
function keeperPlans(a){let by={};a.forEach(p=>(by[team(p)]??=[]).push(p));let blocks=Object.values(by).filter(g=>g.length>=2).map(g=>({g,c:g.slice(0,2).reduce((s,p)=>s+ref(p),0)})).sort((x,y)=>Math.abs(x.c-28)-Math.abs(y.c-28));let out=[];if(blocks[0]){out.push(blocks[0].g[0]);out.push(blocks[0].g[1])}let alt=a.find(p=>!out.includes(p));if(alt)out.push(alt);return out}
function render(){document.body.innerHTML=`<div class="fa-shell"><header><div class="brand"><b>FANTABBA</b><span>AUCTION INTELLIGENCE · 8×500</span></div><nav>${[['war','WAR ROOM'],['plan','PIANO'],['builder','BUILDER'],['list','LISTONE'],['sim','SIMULATORE'],['tools','TOOLS']].map(([k,v])=>`<button class="nav ${S.view===k?'active':''}" data-view="${k}">${v}</button>`).join('')}</nav><div class="budget"><b>${remaining()}</b><small> CREDITI</small></div></header><main id="main"></main></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;render()});({war,plan,builder,list,sim,tools}[S.view]||war)($('#main'))}
function hero(k,h,p){return`<section class="hero"><span class="kicker">${k}</span><h1>${h}</h1><p>${p}</p></section>`}
function war(el){el.innerHTML=hero('LIVE AUCTION','Tu fai l’asta. <em>FantAbba decide.</em>','Cerca un giocatore, inserisci il prezzo appena raggiunto e ottieni un verdetto. Il motore considera valore, budget, slot, reparto e sostituti. Non devi conoscere tu la strategia.')+`<section class="panel war-grid"><div><label>GIOCATORE</label><input id="ws" placeholder="Malen, Lautaro, Yıldız…" autocomplete="off"><div id="suggest"></div></div><div><label>PREZZO ATTUALE</label><div class="price-input"><input id="wp" type="number" min="1" value="20"><span>CR</span></div></div><button class="primary" id="go">ANALIZZA</button></section><div id="out"></div>`;let s=$('#ws'),sg=$('#suggest');s.oninput=()=>{let q=norm(s.value);if(q.length<2){sg.innerHTML='';return}let a=S.players.filter(p=>norm(name(p)).includes(q)||norm(team(p)).includes(q)).slice(0,10);sg.innerHTML=a.map((p,i)=>`<button data-i="${i}"><b>${esc(name(p))}</b><small>${role(p)} · ${esc(team(p))} · ${ref(p)} CR</small></button>`).join('');sg.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.selected=a[+b.dataset.i];s.value=name(S.selected);sg.innerHTML=''})};$('#go').onclick=()=>{let p=S.selected||S.players.find(x=>norm(name(x))===norm(s.value));if(!p){$('#out').innerHTML='<div class="notice">Seleziona un giocatore dalla ricerca.</div>';return}let price=Number($('#wp').value);let [act,tone,msg]=decision(p,price),lim=maxBid(p),alts=alternatives(p);$('#out').innerHTML=`<section class="decision ${tone}"><div class="decision-grid"><div><small>DECISIONE</small><strong>${act}</strong></div><div><small>PREZZO ORA</small><strong>${price} CR</strong></div><div><small>RIFERIMENTO</small><strong>${ref(p)} CR</strong></div><div><small>TUO LIMITE</small><strong>${lim} CR</strong></div></div><h2>${esc(name(p))}</h2><p>${esc(msg)}</p><div class="advice"><b>PIANO DI CONTINUITÀ</b><br>Se perdi ${esc(name(p))}: ${alts.map((x,i)=>`<strong>${i+1}. ${esc(name(x))} (${ref(x)} CR)</strong>`).join(' · ')||'nessun sostituto disponibile'}</div></section>`}}
function plan(el){let rows=['P','D','C','A'].map(r=>{let t=targetSet(r);return`<div class="roster-section"><h3>${CFG.names[r]} <span>${CFG.guide[r]} CR guida</span></h3><div class="players">${t.map((p,i)=>`<div class="player"><div><b>${i===0?'TARGET':i===1?'PIANO B':'PIANO C'}</b><br>${esc(name(p))}</div><span>${esc(team(p))}<br>${tier(p)}</span><strong>${ref(p)}</strong></div>`).join('')}</div></div>`}).join('');el.innerHTML=hero('AUTOPILOT','Il piano lo decide FantAbba.','Non devi compilare una lista di nomi. Il motore costruisce una gerarchia di obiettivi e tre sostituti per ogni reparto.')+`<div class="panel"><b>STRUTTURA INIZIALE</b><p>35 P · 95 D · 160 C · 210 A. È il benchmark mediano delle aste reali 8×500, non una regola rigida.</p></div>${rows}`}
function builder(el){el.innerHTML=hero('OPTIMIZER','Una rosa completa. <em>Non 25 giocatori a caso.</em>','Il Builder ottimizza per budget, ruolo, fasce, coperture e valore. I portieri sono trattati come un blocco; ogni reparto deve avere una struttura economica plausibile.')+`<section class="panel controls"><select id="bs"><option value="balanced">EQUILIBRATA</option><option value="attack">ATTACCO PREMIUM</option><option value="mid">CENTROCAMPO PREMIUM</option><option value="value">VALUE / PROFONDITÀ</option></select><button class="primary" id="build">GENERA ROSA</button></section><div id="bo"></div>`;$('#build').onclick=build}
function pick(r,n,min,max,used){let a=pool(r).filter(p=>!used.has(p)&&ref(p)>=min&&ref(p)<=max).sort((x,y)=>value(y)-value(x));return a.slice(0,n)}
function build(){let strat=$('#bs').value,used=new Set(),r=[];let B=strat==='attack'?{P:30,D:85,C:145,A:240}:strat==='mid'?{P:32,D:90,C:178,A:200}:strat==='value'?{P:30,D:105,C:165,A:200}:CFG.guide;
// goalkeeper block: one starter plus his cover, or cheapest coherent block
let ks=pool('P').slice().sort((a,b)=>value(b)-value(a));let groups={};ks.forEach(p=>(groups[team(p)]??=[]).push(p));let blocks=Object.values(groups).filter(g=>g.length>=2).map(g=>g.slice(0,2)).sort((a,b)=>Math.abs(a.reduce((s,p)=>s+ref(p),0)-25)-Math.abs(b.reduce((s,p)=>s+ref(p),0)-25));let kp=blocks[0]||ks.slice(0,2);kp.forEach(p=>{used.add(p);r.push({...p,paid:ref(p)})});let third=ks.find(p=>!used.has(p)&&ref(p)<=8);if(third){used.add(third);r.push({...third,paid:ref(third)})}
const specs={D:[[1,18,32],[2,10,18],[5,2,11]],C:[[2,28,48],[2,15,28],[4,4,15]],A:[[1,strat==='attack'?70:48,120],[2,24,55],[3,4,23]]};for(let roleKey of ['D','C','A'])for(let [n,min,max] of specs[roleKey])pick(roleKey,n,min,max,used).forEach(p=>{used.add(p);r.push({...p,paid:ref(p)})});
for(let roleKey of ['P','D','C','A']){let need=CFG.slots[roleKey]-r.filter(p=>role(p)===roleKey).length;pool(roleKey).filter(p=>!used.has(p)).sort((a,b)=>ref(a)-ref(b)).slice(0,need).forEach(p=>{used.add(p);r.push({...p,paid:Math.max(1,Math.min(ref(p),5))})})}
// Compress expensive picks until total <= 500, replacing with strong cheaper alternatives.
let total=r.reduce((s,p)=>s+p.paid,0);for(let loop=0;loop<100&&total>500;loop++){let old=r.slice().sort((a,b)=>b.paid-a.paid)[0];let repl=pool(role(old)).filter(p=>!used.has(p)&&ref(p)<old.paid).sort((a,b)=>value(b)-value(a))[0];if(!repl){old.paid=Math.max(1,old.paid-2);total=r.reduce((s,p)=>s+p.paid,0);continue}used.delete(old);used.add(repl);let i=r.indexOf(old);r[i]={...repl,paid:Math.max(1,ref(repl))};total=r.reduce((s,p)=>s+p.paid,0)}
// If a role is over its guide, rebalance only by substitutions, never by inventing a negative price.
S.roster=r;S.spent=r.reduce((s,p)=>s+p.paid,0);let valid=r.length===25&&S.spent<=500&&['P','D','C','A'].every(x=>r.filter(p=>role(p)===x).length===CFG.slots[x]);if(!valid){$('#bo').innerHTML='<div class="error"><b>IMPOSSIBILE CON QUESTI DATI</b><p>Il database non permette una rosa valida. Nessun giocatore è stato inventato e il Builder non finge una soluzione.</p></div>';S.roster=[];S.spent=0;return}renderBuilder(r,strat)}
function renderBuilder(r,strat){let rows=['P','D','C','A'].map(x=>{let a=r.filter(p=>role(p)===x);return`<div class="roster-section"><h3>${CFG.names[x]} <span>${a.reduce((s,p)=>s+p.paid,0)} CR</span></h3><div class="players">${a.map(p=>`<div class="player"><div><b>${esc(name(p))}</b><br><span>${esc(team(p))}</span></div><span>${tier(p)}</span><strong>${p.paid}</strong></div>`).join('')}</div></div>`}).join('');$('#bo').innerHTML=`<div class="roster-head"><div><span class="kicker">ROSA GENERATA</span><h2>${r.length}/25 giocatori</h2></div><div class="score">${S.spent}<small> / 500 CR</small></div></div>${rows}<div class="notice"><b>STRATEGIA: ${strat.toUpperCase()}</b><br>La rosa è valida solo se rispetta 3 P · 8 D · 8 C · 6 A e non supera 500 crediti.</div>`}
function list(el){el.innerHTML=hero('DATABASE','Il listone completo.','Ricerca tutti i giocatori, filtra per ruolo e ordina per riferimento, quotazione o valore. I prezzi non vengono nascosti dietro una lista abbreviata.')+`<div class="filters"><input id="lf" placeholder="Cerca giocatore o squadra"><select id="lr"><option value="">TUTTI I RUOLI</option><option>P</option><option>D</option><option>C</option><option>A</option></select><select id="ls"><option value="value">VALORE</option><option value="price">PREZZO</option><option value="quote">QUOTAZIONE</option></select></div><div id="lt" class="table"></div>`;let draw=()=>{let q=norm($('#lf').value),rr=$('#lr').value,ss=$('#ls').value,a=S.players.filter(p=>(!q||norm(name(p)).includes(q)||norm(team(p)).includes(q))&&(!rr||role(p)===rr));a.sort((x,y)=>ss==='price'?ref(x)-ref(y):ss==='quote'?quote(y)-quote(x):value(y)-value(x));$('#lt').innerHTML=`<div class="thead"><span>GIOCATORE</span><span>R</span><span>SQUADRA</span><span>QT</span><span>ASTA</span></div>`+a.map(p=>`<div class="tr"><b>${esc(name(p))}</b><span>${role(p)}</span><span>${esc(team(p))}</span><span>${quote(p)||'—'}</span><span>${ref(p)} · ${real(p)!=null?'REALE':'STIMA'}</span></div>`).join('')};['lf','lr','ls'].forEach(id=>$(id).oninput=draw);draw()}
function sim(el){el.innerHTML=hero('SIMULATORE','Asta plausibile, non numeri casuali.','Ogni prezzo parte dal riferimento del giocatore. La simulazione applica una variazione limitata e tiene conto della fascia: un top non diventa improvvisamente un acquisto da 6 crediti.')+`<section class="panel controls"><button class="primary" id="run">SIMULA 25 ACQUISTI</button></section><div id="so"></div>`;$('#run').onclick=()=>{let a=S.players.filter(p=>ref(p)>0).sort((x,y)=>value(y)-value(x)).slice(0,80);a=a.sort(()=>Math.random()-.5).slice(0,25);let rows=a.map(p=>{let m=ref(p),spread=m>=60?.12:m>=30?.18:.25,price=Math.max(1,Math.round(m*(1+(Math.random()*2-1)*spread)));return`<div><b>${esc(name(p))}</b><span>${role(p)} · riferimento ${m}</span><strong>${price} CR</strong><small>${price>m*1.08?'OVERPAY':price<m*.85?'VALUE':'MERCATO'}</small></div>`}).join('');$('#so').innerHTML=`<div class="simgrid">${rows}</div>`}}
function tools(el){el.innerHTML=hero('TOOLS','Strumenti che servono davvero.','Niente tool decorativi: ogni modulo deve rispondere a una domanda concreta dell’asta.')+`<div class="tool-grid"><article class="tool"><b>PRICE GUARD</b><p>Confronta prezzo attuale, riferimento e tuo limite.</p></article><article class="tool"><b>SUBSTITUTE TREE</b><p>Ogni target ha automaticamente tre sostituti ordinati per valore e costo.</p></article><article class="tool"><b>BUDGET GUARD</b><p>Protegge i crediti minimi necessari per completare tutti gli slot.</p></article><article class="tool"><b>KEEPER BLOCK</b><p>Valuta blocco titolare/riserve invece di scegliere tre portieri indipendenti.</p></article><article class="tool"><b>VALUE HUNTER</b><p>Cerca giocatori con rapporto qualità/prezzo alto.</p></article><article class="tool"><b>SCARCITY</b><p>Individua quando un ruolo sta diventando scarso e cambia il piano di acquisto.</p></article></div>`}
async function boot(){try{let res=await fetch('data/players.json?v=11');if(!res.ok)throw Error('Database non disponibile');let data=await res.json();S.players=Array.isArray(data)?data:[];if(!S.players.length)throw Error('Database vuoto');render()}catch(e){document.body.innerHTML=`<div class="fatal"><h1>FantAbba non riesce a caricare il database</h1><p>${esc(e.message)}</p><code>data/players.json</code></div>`}}
boot();
})();