/* FantAbba V5 — Auction Command Center
   One UI, one engine. Real observed prices are preferred; model values are explicitly estimates.
*/
(()=>{'use strict';
const SLOTS={P:3,D:8,C:8,A:6}, ROLES=['P','D','C','A'];
const stateKey='fantabba-v5-state';
let state=JSON.parse(localStorage.getItem(stateKey)||'null')||{budget:500,credits:500,roster:[],purchases:[],league:8};
let players=[];
const $=id=>document.getElementById(id);
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const role=p=>['P','D','C','A'].includes(p.classicRole)?p.classicRole:['P','D','C','A'].includes(p.classic_role)?p.classic_role:['P','D','C','A'].includes(p.role)?p.role:'C';
const quote=p=>n(p.quotation??p.q??p.price);
const fm=p=>n(p.fantamedia??p.fm??p.fantasyAverage);
const mv=p=>n(p.media??p.mv??p.averageVote);
const apps=p=>n(p.presenze??p.pres??p.appearances);
const goals=p=>n(p.gol??p.goals);
const assists=p=>n(p.assist??p.assists);
function observed(p){for(const k of ['auctionAvg8x500','auction_8x500','price8x500','media8x500','avg8x500','auction8x500']){const v=n(p[k]);if(v>0&&v<=500)return {v,source:'MEDIA 8×500',real:true};}return null}
/* Market estimate: anchored to official quotation and role economics. Never a fake auction average. */
function estimate(p){const r=role(p),q=quote(p);if(!q)return {v:1,source:'STIMA · DATI INSUFFICIENTI',real:false};
 const multipliers={P:1.45,D:1.70,C:2.05,A:2.35};
 const production=(fm(p)?(fm(p)-5.5)*5:0)+(mv(p)?(mv(p)-6)*7:0)+(goals(p)*1.1)+(assists(p)*.6)+(apps(p)?Math.min(apps(p),35)*.18:0);
 let v=q*multipliers[r]+production;
 const cap={P:38,D:65,C:95,A:145}[r];
 v=Math.max(1,Math.min(cap,v));
 return {v:Math.round(v),source:'STIMA CALIBRATA',real:false};}
function market(p){return observed(p)||estimate(p)}
function risk(p){let r=0;if(!observed(p))r+=1;if(apps(p)>0&&apps(p)<20)r+=2;if(p.injured||/injur/i.test(p.status||''))r+=3;if(p.suspended||/suspend/i.test(p.status||''))r+=2;return Math.min(10,r)}
function expected(p){const r=role(p),q=quote(p);let x=(fm(p)*8)+(mv(p)*4)+(goals(p)*1.8)+(assists(p)*1.2)+(apps(p)*.12);if(!x)x=q*({P:1.1,D:1,C:1.25,A:1.5}[r]);return x}
function value(p){return expected(p)/Math.max(market(p).v,1)}
function save(){localStorage.setItem(stateKey,JSON.stringify(state))}
function rosterCount(r){return state.roster.filter(p=>role(p)===r).length}
function slotsLeft(){return Math.max(0,25-state.roster.length)}
function reserve(){let left=slotsLeft();return Math.max(0,left-1)}
function maxBid(){return Math.max(1,state.credits-reserve())}
function decision(p,current){const m=market(p).v, max=maxBid(), c=n(current);if(!c)return {label:'INSERISCI IL PREZZO',cls:'neutral',detail:`Media/valore di riferimento ${m}. Il limite operativo è ${max}.`};if(c>max)return {label:'STOP',cls:'stop',detail:`${c} supera il tuo limite operativo di ${max}. Non compromettere i ${reserve()} slot rimasti.`};if(c>m*1.15)return {label:'PASSA',cls:'stop',detail:`Stai pagando oltre il 115% del valore di riferimento (${m}). Cerca il Piano B.`};if(c>m*1.05)return {label:'ULTIMO RILANCIO',cls:'warn',detail:`Prezzo già sopra il riferimento. Puoi arrivare a ${max}, ma non inseguire.`};if(c>=m*.90)return {label:'RILANCIA',cls:'go',detail:`Prezzo coerente con il mercato. Rilancia solo finché resta sotto ${max}.`};return {label:'RILANCIA FORTE',cls:'hot',detail:`Se il giocatore è un tuo target, il prezzo è sotto il riferimento di mercato.`}}
function alternatives(p){return players.filter(x=>role(x)===role(p)&&norm(x.name)!==norm(p.name)).sort((a,b)=>value(b)-value(a)).slice(0,6)}
function render(){document.body.innerHTML=`<div class="v5"><header><div class="brand"><b>F</b><span>FANTABBA<small>AUCTION INTELLIGENCE</small></span></div><nav>${[['war','WAR ROOM'],['builder','SQUAD BUILDER'],['sim','SIMULATORE'],['list','LISTONE'],['tools','TOOLS']].map(x=>`<button class="nav" data-page="${x[0]}">${x[1]}</button>`).join('')}</nav><div class="credits"><b id="topCr">${state.credits}</b><small>CR</small></div></header><main>
<section id="page-war" class="page active"></section><section id="page-builder" class="page"></section><section id="page-sim" class="page"></section><section id="page-list" class="page"></section><section id="page-tools" class="page"></section></main></div>`;
 document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));show('war');
}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('page-'+page).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('on',x.dataset.page===page));if(page==='war')war();if(page==='builder')builder();if(page==='sim')sim();if(page==='list')list();if(page==='tools')tools()}
function war(){const el=$('page-war');el.innerHTML=`<div class="hero"><div><span>LIVE AUCTION</span><h1>Decidi in pochi secondi.<br><em>Non andare a sensazione.</em></h1><p>Inserisci il prezzo che sta raggiungendo il giocatore. FantAbba confronta prezzo di mercato, budget, slot residui e alternative e ti dà un'azione concreta.</p></div><div class="heroStat"><small>BUDGET OPERATIVO</small><b>${state.credits}</b><span>${slotsLeft()} slot da riempire · limite singolo ${maxBid()}</span></div></div><div class="warGrid"><div class="panel"><div class="panelHead"><b>GIOCATORE ALL'ASTA</b><span>cerca nel listone completo</span></div><input id="warSearch" class="bigInput" placeholder="Es. Malen, Yildiz, Davis..."><div id="warResults"></div></div><div class="panel"><div class="panelHead"><b>DECISIONE</b><span>aggiornata al prezzo inserito</span></div><div id="decision" class="empty">Seleziona un giocatore.</div></div></div>`;const inp=$('warSearch');inp.oninput=()=>warResults(inp.value);warResults('')}
function warResults(q){const a=players.filter(p=>!q||norm(`${p.name} ${p.team}`).includes(norm(q))).sort((a,b)=>value(b)-value(a)).slice(0,12);$('warResults').innerHTML=a.map(p=>{const m=market(p);return `<button class="playerPick" data-name="${esc(p.name)}"><span><b>${esc(p.name)}</b><small>${role(p)} · ${esc(p.team||'')}</small></span><strong>${m.v}<small>${m.source}</small></strong></button>`}).join('');document.querySelectorAll('.playerPick').forEach(b=>b.onclick=()=>selectWar(b.dataset.name))}
function selectWar(name){const p=players.find(x=>norm(x.name)===norm(name));if(!p)return;const m=market(p);$('decision').innerHTML=`<div class="selected"><div class="selectedTop"><div><small>${role(p)} · ${esc(p.team||'')}</small><h2>${esc(p.name)}</h2></div><div class="market"><small>${m.source}</small><b>${m.v}</b></div></div><div class="bidbox"><label>PREZZO ATTUALE DELL'ASTA</label><div><input id="currentBid" type="number" min="1" value="${Math.max(1,Math.round(m.v*.85))}"><span>CR</span><button id="analyze">ANALIZZA</button></div></div><div id="verdict"></div><div class="metrics"><div><small>TUO LIMITE</small><b>${maxBid()}</b></div><div><small>BUDGET</small><b>${state.credits}</b></div><div><small>SLOT</small><b>${slotsLeft()}</b></div><div><small>RISCHIO</small><b>${risk(p)}/10</b></div></div><h3>PIANO B</h3><div class="alts">${alternatives(p).map(x=>`<button data-alt="${esc(x.name)}"><span>${esc(x.name)}<small>${role(x)} · ${esc(x.team||'')}</small></span><b>${market(x).v}</b></button>`).join('')}</div></div>`;analyze(p);$('analyze').onclick=()=>analyze(p);$('currentBid').oninput=()=>analyze(p);document.querySelectorAll('[data-alt]').forEach(b=>b.onclick=()=>selectWar(b.dataset.alt))}
function analyze(p){const c=$('currentBid')?.value||0,d=decision(p,c);$('verdict').innerHTML=`<div class="verdict ${d.cls}"><b>${d.label}</b><span>${d.detail}</span></div>`}
function builder(){const el=$('page-builder');el.innerHTML=`<div class="title"><span>OPTIMIZER</span><h1>Costruisci una rosa <em>realmente acquistabile.</em></h1><p>Non cerca i 25 nomi più forti: risolve il vincolo 3 P · 8 D · 8 C · 6 A e poi migliora la rosa finché il budget lo consente.</p></div><div class="controls"><label>Budget<input id="bud" type="number" value="500" min="25" max="500"></label><label>Strategia<select id="style"><option value="balanced">Bilanciata</option><option value="value">Value</option><option value="safe">Affidabilità</option><option value="top">Top-heavy</option></select></label><button id="generate">GENERA ROSA</button></div><div id="builderResult"></div>`;$('generate').onclick=generate}
function generate(){const budget=Math.min(500,Math.max(25,n($('bud').value)||500)),style=$('style').value;try{const res=optimize(budget,style);renderRoster(res)}catch(e){$('builderResult').innerHTML=`<div class="error"><b>IMPOSSIBILE GENERARE UNA ROSA VALIDA</b><p>${esc(e.message)}</p></div>`}}
function optimize(budget,style){let out={},used=new Set(),spent=0;for(const r of ROLES){const pool=players.filter(p=>role(p)===r).sort((a,b)=>market(a).v-market(b).v);if(pool.length<SLOTS[r])throw Error(`Mancano giocatori ${r}: ${pool.length}/${SLOTS[r]}.`);out[r]=pool.slice(0,SLOTS[r]);out[r].forEach(p=>{used.add(norm(p.name));spent+=market(p).v})}if(spent>budget)throw Error(`Il minimo dei 25 giocatori è ${spent} crediti: il database prezzi/stime non è coerente con il budget.`);const score=p=>style==='value'?value(p)*100:risk(p)*(style==='safe'?-5:-2)+expected(p);let changed=true;while(changed){changed=false;let best=null;for(const r of ROLES){for(let i=0;i<out[r].length;i++){for(const cand of players.filter(p=>role(p)===r&&!used.has(norm(p.name)))){const d=market(cand).v-market(out[r][i]).v;if(spent+d>budget)continue;const gain=score(cand)-score(out[r][i]);const eff=gain/Math.max(1,d);if(gain>0&&(!best||eff>best.eff))best={r,i,cand,d,eff}}}}if(best){used.delete(norm(out[best.r][best.i].name));used.add(norm(best.cand.name));out[best.r][best.i]=best.cand;spent+=best.d;changed=true}}return{out,spent,budget}}
function renderRoster(res){$('builderResult').innerHTML=`<div class="rosterSummary"><div><small>SPESA</small><b>${res.spent}</b><span>/ ${res.budget}</span></div><div><small>AVANZO</small><b>${res.budget-res.spent}</b></div><div><small>VALIDITÀ</small><b>25/25</b></div></div><div class="rosterGrid">${ROLES.map(r=>`<div class="panel"><div class="panelHead"><b>${r}</b><span>${SLOTS[r]} slot</span></div>${res.out[r].map(p=>`<div class="rosterRow"><span><b>${esc(p.name)}</b><small>${esc(p.team||'')}</small></span><strong>${market(p).v}</strong></div>`).join('')}</div>`).join('')}</div>`}
function sim(){const el=$('page-sim');el.innerHTML=`<div class="title"><span>AUCTION LAB</span><h1>Simula un'asta <em>con prezzi di mercato.</em></h1><p>Ogni prezzo parte dal riferimento del giocatore e viene perturbato in modo controllato. Niente più asta con tutti i giocatori a 6 crediti.</p></div><div class="controls"><label>Partecipanti<input id="teams" type="number" value="8" min="2" max="20"></label><label>Budget<input id="simBud" type="number" value="500" min="50" max="1000"></label><label>Agonismo<select id="agg"><option value=".08">Prudente</option><option value=".15" selected>Realistica</option><option value=".23">Aggressiva</option></select></label><button id="runSim">SIMULA ASTA</button></div><div id="simResult"></div>`;$('runSim').onclick=runSim}
function runSim(){const teams=Math.max(2,Math.min(20,n($('teams').value)||8)),bud=Math.max(50,n($('simBud').value)||500),vol=n($('agg').value)||.15;const pool=[...players].sort((a,b)=>value(b)-value(a)).slice(0,Math.min(players.length,80));const rows=pool.slice(0,35).map(p=>{const m=market(p).v;const skew=(Math.random()*2-1)*vol;const price=Math.max(1,Math.round(m*(1+skew)));return {p,price}}).sort((a,b)=>b.price-a.price);$('simResult').innerHTML=`<div class="simNote">${teams} squadre · ${bud} crediti · prezzi ancorati al mercato · volatilità ${Math.round(vol*100)}%</div><div class="simTable">${rows.map(x=>`<div><span><b>${esc(x.p.name)}</b><small>${role(x.p)} · mercato ${market(x.p).v}</small></span><strong>${x.price}</strong><em>${x.price<=market(x.p).v?'SOTTO MERCATO':x.price>market(x.p).v*1.15?'OVERPAY':'MERCATO'}</em></div>`).join('')}</div>`}
function list(){const el=$('page-list');el.innerHTML=`<div class="title"><span>DATABASE</span><h1>Il listone, <em>senza limiti artificiali.</em></h1></div><div class="filters"><input id="ls" placeholder="Cerca giocatore o squadra"><select id="lr"><option value="">Tutti</option>${ROLES.map(r=>`<option>${r}</option>`).join('')}</select></div><div class="tableWrap"><table><thead><tr><th>Giocatore</th><th>Ruolo</th><th>Squadra</th><th>Qt.</th><th>Prezzo</th><th>Fonte</th><th>Value</th></tr></thead><tbody id="tbody"></tbody></table></div>`;$('ls').oninput=drawList;$('lr').onchange=drawList;drawList()}
function drawList(){const q=norm($('ls').value),r=$('lr').value;const a=players.filter(p=>(!q||norm(`${p.name} ${p.team}`).includes(q))&&(!r||role(p)===r)).sort((a,b)=>value(b)-value(a));$('tbody').innerHTML=a.map(p=>{const m=market(p);return`<tr><td><b>${esc(p.name)}</b></td><td>${role(p)}</td><td>${esc(p.team||'—')}</td><td>${quote(p)||'—'}</td><td><b>${m.v}</b></td><td><span class="tag ${m.real?'real':''}">${m.source}</span></td><td>${value(p).toFixed(2)}</td></tr>`}).join('')}
function tools(){const el=$('page-tools');const items=[['value','Value Hunter','Chi produce più valore per credito'],['price','Price Map','Prezzi di mercato e stime, ordinati per reparto'],['risk','Risk Radar','Rischio presenze/status/dati'],['sleepers','Sleeper Radar','Value economico sotto una soglia'],['keepers','Portieri','Tutti i portieri con ranking e prezzi'],['pairing','Abbinamenti','Candidati complementari nello stesso reparto'],['planb','Piano B','Alternative ordinate per costo e valore']];el.innerHTML=`<div class="title"><span>ANALYTICS</span><h1>Tools che servono <em>durante l'asta.</em></h1></div><div class="toolGrid">${items.map(x=>`<button class="tool" data-tool="${x[0]}"><b>${x[1]}</b><span>${x[2]}</span><i>→</i></button>`).join('')}</div><div id="toolOut"></div>`;document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>tool(b.dataset.tool))}
function tool(type){let a=[...players];if(type==='value')a.sort((x,y)=>value(y)-value(x));if(type==='price')a.sort((x,y)=>market(y).v-market(x).v);if(type==='risk')a.sort((x,y)=>risk(y)-risk(x));if(type==='sleepers')a=a.filter(p=>market(p).v<=15).sort((x,y)=>value(y)-value(x));if(type==='keepers')a=a.filter(p=>role(p)==='P').sort((x,y)=>value(y)-value(x));if(type==='pairing')a.sort((x,y)=>value(y)-value(x));if(type==='planb')a.sort((x,y)=>market(x).v-market(y).v);$('toolOut').innerHTML=`<div class="toolResult"><div class="panelHead"><b>${type.toUpperCase()}</b><span>${a.length} giocatori</span></div>${a.map(p=>`<div class="toolRow"><span><b>${esc(p.name)}</b><small>${role(p)} · ${esc(p.team||'')} · rischio ${risk(p)}/10</small></span><strong>${market(p).v}<small>${market(p).source}</small></strong></div>`).join('')}</div>`}
async function init(){try{const r=await fetch('data/players.json?v=5',{cache:'no-store'});players=await r.json();if(!Array.isArray(players)||players.length<100)throw Error('Database listone non valido');render()}catch(e){document.body.innerHTML=`<div style="padding:40px;color:white;font-family:system-ui"><h1>FantAbba non ha caricato il database</h1><p>${esc(e.message)}</p></div>`}}
init();
})();