(()=>{
'use strict';
const $=id=>document.getElementById(id),R=['P','D','C','A'],L={P:3,D:8,C:8,A:6},TARGET={P:35,D:95,C:160,A:210};
const N=v=>Number(v)||0,norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const O=()=>window.FANTABBA_CLASSIC_ROLE_OVERRIDES||{};
const role=p=>{const e=p.classicRole||p.classic_role||p.roleClassic;if(['P','D','C','A'].includes(e))return e;return O()[norm(p.name)]||p.role};
const DATA=()=>{try{return typeof players!=='undefined'&&Array.isArray(players)?players:[]}catch{return[]}};
const STATE=()=>{try{return JSON.parse(localStorage.getItem('fantabbaState')||'{"credits":500,"roster":{"P":[],"D":[],"C":[],"A":[]},"logs":[],"opponents":[]}')}catch{return{credits:500,roster:{P:[],D:[],C:[],A:[]},logs:[],opponents:[]}}};
const used=()=>Object.values(STATE().roster||{}).flat().map(x=>norm(x.name));
const sold=p=>STATE().logs.some(l=>!l.mine&&norm(l.player)===norm(p.name));
const quo=p=>N(p.quotation??p.price),fvm=p=>N(p.fvm),pres=p=>N(p.presenze??p.appearances),mv=p=>N(p.media??p.mediaVoto),fm=p=>N(p.fantamedia??p.fantaMedia),goals=p=>N(p.gol??p.goals),assists=p=>N(p.assist??p.assists),tit=p=>N(p.titolarita??p.starter),fix=p=>N(p.fixtureScore);
const realAvg=p=>{const a=N(p.auctionAvg8x500??p.auctionAvg??p.averageAuction);const season=String(p.auctionSeason||p.auctionSeason8x500||'');return a>0&&(!season||!season.includes('2025'))?a:0};
const observedRatio=r=>{const a=DATA().filter(p=>role(p)===r&&realAvg(p)>0&&quo(p)>0).map(p=>realAvg(p)/quo(p)).sort((a,b)=>a-b);if(!a.length)return {P:1.55,D:1.75,C:2.20,A:2.50}[r]||2;return a[Math.floor(a.length/2)]};
const percentile=(p,r)=>{const a=DATA().filter(x=>role(x)===r&&quo(x)>0).map(x=>quo(x)).sort((a,b)=>a-b);if(!a.length)return .5;let i=a.findIndex(x=>x>=quo(p));if(i<0)i=a.length-1;return i/Math.max(1,a.length-1)};
const estimate=p=>{const r=role(p),ratio=observedRatio(r),pct=percentile(p,r);let raw=quo(p)*ratio*(.78+.34*pct);if(r==='P')raw=Math.min(raw,45);if(r==='D')raw=Math.min(raw,55);if(r==='C')raw=Math.min(raw,90);if(r==='A')raw=Math.min(raw,130);return Math.max(1,Math.round(raw))};
const cost=p=>{const a=realAvg(p);return {value:a||estimate(p),real:a>0,source:a>0?'MEDIA 8×500':'STIMA MODELLO'}};
const expected=p=>{let x=fm(p)*7+mv(p)*2+Math.min(pres(p),38)*.10+goals(p)*1.8+assists(p)*1.25+tit(p)*.035+fix(p)*1.3;if(!x)x=fvm(p)*.035+quo(p)*.55;return x};
const risk=p=>Math.min(5,(realAvg(p)?0:.35)+(pres(p)?(pres(p)<18?2:pres(p)<25?1:0):1)+(tit(p)?(tit(p)<60?1:0):.5)+(mv(p)?(mv(p)<6.15?1:0):.4));
const value=p=>expected(p)/Math.max(cost(p).value,1);
const available=r=>DATA().filter(p=>p.name&&role(p)===r&&!used().includes(norm(p.name))&&!sold(p.name));
function score(p,style){let s=expected(p)+value(p)*10-risk(p)*2;if(style==='value')s+=value(p)*20;if(style==='stars')s+=expected(p)*.12;if(style==='safe')s-=risk(p)*6;if(style==='calendar')s+=fix(p)*2;return s}
function roleDP(r,k,budget,style){const arr=available(r).map(p=>{const c=cost(p);return {...p,_cost:c.value,_real:c.real,_source:c.source,_score:score(p,style),_risk:risk(p),_value:value(p),_exp:expected(p)}}).filter(p=>p._cost<=budget).sort((a,b)=>b._score-a._score).slice(0,140);const dp=Array.from({length:k+1},()=>new Map());dp[0].set(0,{score:0,items:[]});for(const p of arr){for(let j=k;j>=1;j--){const prev=[...dp[j-1].entries()];for(const [b,s] of prev){const nb=b+p._cost;if(nb>budget)continue;const ns={score:s.score+p._score,items:s.items.concat(p)};const old=dp[j].get(nb);if(!old||ns.score>old.score)dp[j].set(nb,ns)}}}return dp[k]}
function optimize(budget,style){let states=[{cost:0,score:0,g:{}}];for(const r of R){const opts=roleDP(r,L[r],budget,style);if(!opts)return null;const next=[];for(const s of states)for(const [c,o] of opts){if(s.cost+c<=budget)next.push({cost:s.cost+c,score:s.score+o.score,g:{...s.g,[r]:o}})}const best=new Map;for(const s of next){const old=best.get(s.cost);if(!old||s.score>old.score)best.set(s.cost,s)}states=[...best.values()].sort((a,b)=>b.score-a.score).slice(0,220);if(!states.length)return null}return states.sort((a,b)=>b.score-a.score||a.cost-b.cost)[0]}
function build(){const budget=Math.max(25,Math.min(500,N($('buildBudget')?.value)||500)),style=$('buildStyle')?.value||'balanced';const best=optimize(budget,style);if(!best){$('builderResult').className='builder-result';$('builderResult').innerHTML='<div class="advice bad"><b>NESSUNA ROSA REALIZZABILE</b><p>Con i prezzi disponibili non posso garantire 25 slot entro il budget. Non invento prezzi.</p></div>';return}const flat=R.flatMap(r=>best.g[r].items),real=flat.filter(p=>realAvg(p)).length,spend=best.cost;let h=`<div class="build-total"><div><b>ROSA OTTIMIZZATA 25/25</b><small>3 P · 8 D · 8 C · 6 A · budget rispettato</small></div><strong>${spend} / ${budget} CR</strong></div><div class="builder-note"><b>Motore:</b> ottimizzazione globale dei 25 slot. I prezzi reali 8×500 hanno priorità assoluta; dove il dato non esiste viene usata una stima calibrata e marcata. <b>${real}/25</b> prezzi sono realmente osservati.</div><div class="build-grid">`;for(const r of R){h+=`<div class="build-card"><h3>${r} ${best.g[r].items.length}/${L[r]}</h3>`+best.g[r].items.sort((a,b)=>b._score-a._score).map(p=>`<div class="plan-item"><span><b>${esc(p.name)}</b> · ${esc(p.team||'')} <small class="price-source ${p._real?'real':'estimate'}">${p._source}</small></span><b>${p._cost}</b></div>`).join('')+'</div>'}h+=`</div><div class="builder-footer"><span>SPESA <b>${spend}</b></span><span>AVANZO <b>${budget-spend}</b></span><span>MEDIA REALI <b>${real}/25</b></span></div>`;$('builderResult').className='builder-result';$('builderResult').innerHTML=h}
function render(title,sub,rows,extra=''){const o=$('toolOutput');if(!o)return;o.className='panel tool-output';o.innerHTML=`<div class="tool-result-head"><span class="kicker">FANTABBA PRO</span><h2>${title}</h2><p>${sub}</p>${extra}</div><div class="tool-results" id="toolRows">${rows.map(x=>`<div class="plan-item"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')||'<div class="empty">Nessun risultato con i dati attuali.</div>'}</div>`}
function toolRows(ps, mapper){return ps.map(mapper)}
function tools(k){const all=DATA().filter(p=>p.name&&!used().includes(norm(p.name))&&!sold(p));
 if(k==='budget')return render('Budget Guard','Protegge i crediti minimi necessari per completare tutti gli slot, reparto per reparto.',R.map(r=>{const s=STATE(),need=Math.max(0,L[r]-(s.roster[r]||[]).length),min=Math.max(need,need*2);return[`${r} · ${need} slot`,`${Math.min(s.credits,Math.round(min))} CR riserva minima`]}));
 if(k==='priceguard')return render('Price Guard','Confronta il prezzo osservato con il limite operativo. Media = dato reale; Stima = modello.',toolRows(all.sort((a,b)=>value(b)-value(a)),p=>{const c=cost(p);return[`${esc(p.name)} · ${role(p)} · ${esc(p.team||'')}`,`${c.value} CR · ${c.source}`]}));
 if(k==='sleepers')return render('Sleeper Radar','Cerca valore economico: non basta essere economici, serve rendimento atteso e rischio accettabile.',toolRows(all.filter(p=>fvm(p)>0).sort((a,b)=>(value(b)-risk(b)*.1)-(value(a)-risk(a)*.1)),p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team||'')}`,`${cost(p).value} CR · value ${value(p).toFixed(2)} · rischio ${risk(p).toFixed(1)}/5`]));
 if(k==='keepers'){const q=all.filter(p=>role(p)==='P').sort((a,b)=>value(b)-value(a)),z=[];for(let i=0;i<q.length;i++)for(let j=i+1;j<q.length;j++)if(q[i].team&&q[i].team===q[j].team)z.push([`${esc(q[i].name)} + ${esc(q[j].name)}`,`${cost(q[i]).value+cost(q[j]).value} CR · ${esc(q[i].team)}`]);return render('Griglia Portieri','Mostra tutte le coppie titolare/riserva dello stesso club disponibili nel database, ordinate per valore.',z)}
 if(k==='fixture')return render('Fixture Optimizer','Mostra tutti i giocatori per cui esiste un indice calendario nel database. Nessun incrocio viene inventato.',toolRows(all.filter(p=>fix(p)>0).sort((a,b)=>fix(b)-fix(a)),p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team||'')}`,`fixture ${fix(p).toFixed(1)}`]));
 if(k==='risk')return render('Risk Radar','Rischio di acquisto calcolato su presenze, titolarità, rendimento e qualità del prezzo.',toolRows(all.sort((a,b)=>risk(b)-risk(a)),p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team||'')}`,`${risk(p).toFixed(1)}/5 · ${cost(p).source}`]));
 if(k==='value')return render('Value Finder','Tutti i giocatori ordinati per rendimento atteso per credito, corretto per rischio.',toolRows(all.sort((a,b)=>(value(b)-risk(b)*.08)-(value(a)-risk(a)*.08)),p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team||'')}`,`${value(p).toFixed(2)} · ${cost(p).value} CR`]));
 if(k==='pairing'){const z=[];for(const r of ['D','C','A']){const q=all.filter(p=>role(p)===r).sort((a,b)=>value(b)-value(a));for(let i=0;i<q.length;i++)for(let j=i+1;j<q.length;j++)if(q[i].team&&q[j].team&&q[i].team!==q[j].team)z.push([`${esc(q[i].name)} + ${esc(q[j].name)}`,`${Math.round(cost(q[i]).value+cost(q[j]).value)} CR · ${r} · diversificata`])}return render('Pairing','Tutte le combinazioni disponibili tra squadre diverse, ordinate per valore complessivo.',z.sort((a,b)=>Number(a[1])-Number(b[1])))}
 return render('Scenario Engine','Piano B completo: per ogni ruolo puoi cercare alternative al target senza limitarti ai primi risultati alfabetici.',toolRows(all.sort((a,b)=>value(b)-value(a)),p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team||'')}`,`limite operativo ${Math.max(1,Math.round(cost(p).value*1.05))} CR`]))
}
function bind(){const b=$('buildBtn');if(b)b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();build()},true);document.querySelectorAll('.tool[data-tool]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();tools(b.dataset.tool)},true))}
window.fantabbaBuildPro=build;window.fantabbaToolsPro=tools;const boot=()=>setTimeout(bind,500);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();