(()=>{
'use strict';
const $=id=>document.getElementById(id),R=['P','D','C','A'],L={P:3,D:8,C:8,A:6},TARGET={P:35,D:95,C:160,A:210};
const N=v=>Number(v)||0,norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const O=()=>window.FANTABBA_CLASSIC_ROLE_OVERRIDES||{};
const role=p=>{const e=p.classicRole||p.classic_role||p.roleClassic;if(['P','D','C','A'].includes(e))return e;return O()[norm(p.name)]||p.role};
const DATA=()=>{try{return typeof players!=='undefined'&&Array.isArray(players)?players:[]}catch{return[]}};
const STATE=()=>{try{return JSON.parse(localStorage.getItem('fantabbaState')||'{"credits":500,"roster":{"P":[],"D":[],"C":[],"A":[]},"logs":[],"opponents":[]}')}catch{return{credits:500,roster:{P:[],D:[],C:[],A:[]},logs:[],opponents:[]}}};
const used=()=>Object.values(STATE().roster||{}).flat().map(x=>norm(x.name));
const sold=p=>STATE().logs.some(l=>!l.mine&&norm(l.player)===norm(p.name));
const quo=p=>N(p.quotation??p.price),fvm=p=>N(p.fvm),pres=p=>N(p.presenze??p.appearances),mv=p=>N(p.media??p.mediaVoto),fm=p=>N(p.fantamedia??p.fantaMedia),goals=p=>N(p.gol??p.goals),assists=p=>N(p.assist??p.assists),tit=p=>N(p.titolarita??p.starter),fix=p=>N(p.fixtureScore);
const realAvg=p=>{const a=N(p.auctionAvg8x500??p.auctionAvg??p.averageAuction);if(!a)return 0;const season=String(p.auctionSeason||'');if(season.includes('2025'))return 0;return a};
const observedRatio=r=>{const a=DATA().filter(p=>role(p)===r&&realAvg(p)>0&&quo(p)>0).map(p=>realAvg(p)/quo(p)).sort((a,b)=>a-b);if(!a.length)return r==='P'?1.55:r==='D'?1.75:r==='C'?2.2:2.5;return a[Math.floor(a.length/2)]};
const percentile=(p,r)=>{const a=DATA().filter(x=>role(x)===r&&quo(x)>0).map(x=>quo(x)).sort((a,b)=>a-b);if(!a.length)return .5;let i=a.findIndex(x=>x>=quo(p));if(i<0)i=a.length-1;return i/Math.max(1,a.length-1)};
const estimate=p=>{const r=role(p),ratio=observedRatio(r),pct=percentile(p,r);let raw=quo(p)*ratio*(.78+.34*pct);if(r==='P')raw=Math.min(raw,45);if(r==='D')raw=Math.min(raw,55);if(r==='C')raw=Math.min(raw,85);if(r==='A')raw=Math.min(raw,125);return Math.max(1,Math.round(raw))};
const cost=p=>realAvg(p)||estimate(p),source=p=>realAvg(p)?'MEDIA 8×500':'STIMA';
const expected=p=>{let x=fm(p)*7+mv(p)*2+Math.min(pres(p),38)*.10+goals(p)*1.8+assists(p)*1.25+tit(p)*.035+fix(p)*1.3;if(!x)x=fvm(p)*.035+quo(p)*.55;return x};
const risk=p=>Math.min(5,(realAvg(p)?0:.35)+(pres(p)?(pres(p)<18?2:pres(p)<25?1:0):1)+(tit(p)?(tit(p)<60?1:0):.5)+(mv(p)?(mv(p)<6.15?1:0):.4));
const value=p=>expected(p)/Math.max(cost(p),1);
const available=r=>DATA().filter(p=>p.name&&role(p)===r&&!used().includes(norm(p.name))&&!sold(p));
function score(p,style){let s=expected(p)+value(p)*10-risk(p)*2;if(style==='value')s+=value(p)*20;if(style==='stars')s+=expected(p)*.12;if(style==='safe')s-=risk(p)*6;if(style==='calendar')s+=fix(p)*2;return s}
function roleDP(r,k,budget,style){const arr=available(r).map(p=>({...p,_cost:cost(p),_real:!!realAvg(p),_score:score(p,style),_risk:risk(p),_value:value(p),_exp:expected(p)})).filter(p=>p._cost<=budget).sort((a,b)=>b._score-a._score).slice(0,90);const dp=Array.from({length:k+1},()=>new Map());dp[0].set(0,{score:0,items:[]});for(const p of arr){for(let j=k;j>=1;j--){const prev=[...dp[j-1].entries()];for(const [b,s] of prev){const nb=b+p._cost;if(nb>budget)continue;const ns={score:s.score+p._score,items:s.items.concat(p)};const old=dp[j].get(nb);if(!old||ns.score>old.score)dp[j].set(nb,ns)}}}return dp[k]}
function optimize(budget,style){let states=[{cost:0,score:0,g:{}}];for(const r of R){const opts=roleDP(r,L[r],budget,style);if(!opts)return null;const next=[];for(const s of states)for(const [c,o] of opts){if(s.cost+c<=budget)next.push({cost:s.cost+c,score:s.score+o.score,g:{...s.g,[r]:o}})}const best=new Map;for(const s of next){const old=best.get(s.cost);if(!old||s.score>old.score)best.set(s.cost,s)}states=[...best.values()].sort((a,b)=>b.score-a.score).slice(0,180);if(!states.length)return null}return states.sort((a,b)=>b.score-a.score||a.cost-b.cost)[0]}
function build(){const budget=Math.max(25,Math.min(500,N($('buildBudget')?.value)||500)),style=$('buildStyle')?.value||'balanced';const best=optimize(budget,style);if(!best){$('builderResult').className='builder-result';$('builderResult').innerHTML='<div class="advice bad"><b>NESSUNA ROSA REALIZZABILE</b><p>Con i prezzi disponibili non posso garantire 25 slot entro il budget. Non invento prezzi.</p></div>';return}const flat=R.flatMap(r=>best.g[r].items),real=flat.filter(p=>realAvg(p)).length,spend=best.cost;let h=`<div class="build-total"><div><b>ROSA OTTIMIZZATA 25/25</b><small>3 P · 8 D · 8 C · 6 A · budget rispettato</small></div><strong>${spend} / ${budget} CR</strong></div><div class="builder-note"><b>Motore:</b> ottimizzazione globale dei 25 slot, prezzi reali 8×500 quando presenti, stime calibrate sulla curva osservata del ruolo, rendimento atteso, rischio e stile selezionato. <b>${real}/25</b> prezzi sono reali; il resto è STIMA.</div><div class="build-grid">`;for(const r of R){h+=`<div class="build-card"><h3>${r} ${best.g[r].items.length}/${L[r]}</h3>`+best.g[r].items.sort((a,b)=>b._score-a._score).map(p=>`<div class="plan-item"><span><b>${esc(p.name)}</b> · ${esc(p.team)} <small class="price-source ${realAvg(p)?'real':'estimate'}">${source(p)}</small></span><b>${p._cost}</b></div>`).join('')+'</div>'}h+=`</div><div class="builder-footer"><span>SPESA <b>${spend}</b></span><span>AVANZO <b>${budget-spend}</b></span><span>MEDIA REALI <b>${real}/25</b></span><span>VALUE <b>${flat.reduce((a,p)=>a+p._value,0).toFixed(1)}</b></span></div>`;$('builderResult').className='builder-result';$('builderResult').innerHTML=h}
function render(title,sub,rows,extra=''){const o=$('toolOutput');if(!o)return;o.className='panel tool-output';o.innerHTML=`<div class="tool-result-head"><span class="kicker">FANTABBA PRO</span><h2>${title}</h2><p>${sub}</p>${extra}</div><div class="tool-results">${rows.map(x=>`<div class="plan-item"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')||'<div class="empty">Nessun risultato con i dati attuali.</div>'}</div>`}
function tools(k){const ps=DATA().filter(p=>p.name&&!used().includes(norm(p.name))&&!sold(p));if(k==='budget'){const s=STATE();return render('Budget Guard','Non guarda solo la percentuale: protegge i crediti necessari per chiudere tutti gli slot.',R.map(r=>{const need=Math.max(0,L[r]-(s.roster[r]||[]).length),target=Math.round(TARGET[r]/L[r]*need);return[`${r} · ${need} slot`,`${Math.min(s.credits,Math.max(need,target))} CR`] }))}
if(k==='priceguard'){return render('Price Guard','Il numero da guardare durante l’asta: prezzo corrente vs media reale, con margine e fabbisogno rosa.',ps.sort((a,b)=>value(b)-value(a)).slice(0,35).map(p=>[`${esc(p.name)} · ${role(p)} · ${source(p)}`,`media ${realAvg(p)||'N/D'} · stop ${Math.round(cost(p)*1.06)}`]))}
if(k==='sleepers'){return render('Sleeper Radar','Non cerca “nomi strani”: cerca rapporto rendimento/prezzo e rischio accettabile.',ps.filter(p=>fvm(p)>0).sort((a,b)=>(value(b)-risk(b)*.10)-(value(a)-risk(a)*.10)).slice(0,30).map(p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team)}`,`${cost(p)} CR · rischio ${risk(p).toFixed(1)}/5`]))}
if(k==='keepers'){const q=ps.filter(p=>role(p)==='P').sort((a,b)=>value(b)-value(a)),z=[];for(let i=0;i<q.length;i++)for(let j=i+1;j<q.length;j++)if(q[i].team===q[j].team)z.push([`${esc(q[i].name)} + ${esc(q[j].name)}`,`${cost(q[i])+cost(q[j])} CR · ${esc(q[i].team)}`]);return render('Griglia Portieri','Priorità alla copertura reale: titolare + riserva dello stesso club quando disponibile.',z.slice(0,20))}
if(k==='fixture'){const q=ps.filter(p=>fix(p)>0).sort((a,b)=>fix(b)-fix(a)).slice(0,30);return render('Fixture Optimizer','Usa il calendario solo quando il database contiene un indice reale; non inventa incroci.',q.map(p=>[`${esc(p.name)} · ${esc(p.team)}`,`fixture ${fix(p).toFixed(1)}`]))}
if(k==='risk'){return render('Risk Radar','Rischio di acquisto: presenze, titolarità, rendimento e qualità dei dati.',ps.map(p=>[p,risk(p)]).sort((a,b)=>b[1]-a[1]).slice(0,30).map(x=>[`${esc(x[0].name)} · ${role(x[0])}`,`${x[1].toFixed(1)}/5`]))}
if(k==='value'){return render('Value Finder','Valore per credito: rendimento atteso diviso costo, corretto per rischio.',ps.sort((a,b)=>(value(b)-risk(b)*.08)-(value(a)-risk(a)*.08)).slice(0,35).map(p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team)}`,`${value(p).toFixed(2)} · ${cost(p)} CR`]))}
if(k==='pairing'){const z=[];for(const r of ['D','C','A']){const q=ps.filter(p=>role(p)===r).sort((a,b)=>value(b)-value(a)).slice(0,16);for(let i=0;i<q.length;i++)for(let j=i+1;j<q.length;j++)if(q[i].team!==q[j].team)z.push([`${esc(q[i].name)} + ${esc(q[j].name)}`,`${Math.round(cost(q[i])+cost(q[j]))} CR · diversificata`])}return render('Pairing','Costruisce coperture di reparto diversificando le squadre; non promette bonus inesistenti.',z.slice(0,25))}
const q=ps.sort((a,b)=>value(b)-value(a)).slice(0,30);return render('Scenario Engine','Se perdi un target, ordina il Piano B per ruolo, valore e costo.',q.map(p=>[`${esc(p.name)} · ${role(p)} · ${esc(p.team)}`,`limite ${Math.round(cost(p)*1.05)} CR`]))}
function bind(){const b=$('buildBtn');if(b){b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();build()},true)}document.querySelectorAll('.tool[data-tool]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();tools(b.dataset.tool)},true));}
window.fantabbaBuildPro=build;window.fantabbaToolsPro=tools;const boot=()=>setTimeout(bind,500);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();})();