const CFG={budget:500,slots:{P:3,D:8,C:8,A:6},names:{P:'Portieri',D:'Difensori',C:'Centrocampisti',A:'Attaccanti'},bench:{P:35,D:95,C:160,A:210}};
const S={players:[],roster:[],spent:0,view:'war',strategy:'balanced',selected:null};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function role(p){const r=String(p.role||p.ruolo||p.position||'').toUpperCase();return ['P','D','C','A'].find(x=>r.startsWith(x))||''}
function pname(p){return p.name||p.nome||p.player||p.fullName||p.cognome||'Sconosciuto'}function team(p){return p.team||p.squadra||p.club||''}
function quote(p){return Number(p.quotation??p.quotazione??p.q??p.fvm??0)||0}function real(p){const v=Number(p.auctionAvg8x500??p.avg8x500??p.price8x500??p.asta8x500);return Number.isFinite(v)&&v>0?v:null}
function ref(p){const r=role(p),a=real(p);if(a)return a;const q=quote(p);const mult={P:1.35,D:1.55,C:2.0,A:2.55}[r]||1.5;const cap={P:32,D:55,C:78,A:125}[r]||60;return Math.max(1,Math.min(cap,Math.round(q*mult)))}
function source(p){return real(p)?'MEDIA REALE 8×500':'STIMA — DATI INSUFFICIENTI'}
function quality(p){const q=quote(p),a=real(p);const f=Number(p.fvm||p.FVM||0)||0;return (a?55:38)+Math.min(25,q)+Math.min(20,f/10)}
function score(p){return quality(p)+ref(p)*.35}
function playersBy(r){return S.players.filter(p=>role(p)===r)}
function tier(p){const q=quote(p);if(q>=30)return'TOP';if(q>=15)return'SEMITOP';if(q>=6)return'VALUE';return'SCOMMESSA'}
function remaining(){return CFG.budget-S.spent}
function minReserve(roster=S.roster){return Math.max(0,25-roster.length)}
function maxBidFor(p){const r=role(p),used=S.roster.filter(x=>role(x)===r).length,leftSlots=CFG.slots[r]-used,left=remaining(),reserve=Math.max(0,(25-S.roster.length-1));const roleSpent=S.roster.filter(x=>role(x)===r).reduce((a,x)=>a+x.paid,0);const roleBudget=CFG.bench[r];const roleRoom=Math.max(1,roleBudget-roleSpent+Math.max(0,roleBudget*.12));const market=ref(p);const scarcity=leftSlots<=2?1.05:1;return Math.max(1,Math.min(left-reserve,Math.round(Math.min(market*1.08,roleRoom)*scarcity)))}
function decision(p,current){const limit=maxBidFor(p),r=role(p),market=ref(p),premium=(current-market)/Math.max(1,market);if(current>limit)return['STOP','bad','Non andare oltre. Il capitale residuo vale più di questo acquisto.'];if(current>=limit*.94)return['ULTIMO RILANCIO','warn','Un solo rilancio. Se qualcuno sale ancora, esci e passa al piano alternativo.'];if(current<=market*.78)return['RILANCIA FORTE','good','Prezzo sotto mercato: qui puoi aumentare la pressione senza rompere il piano.'];if(current<=market)return['RILANCIA','good','Prezzo ancora sostenibile rispetto al riferimento e al tuo budget.'];return['RILANCIA CON CAUTELA','warn',premium<.08?'Leggero sovrapprezzo: continua solo se il profilo è prioritario.':'Stai pagando un premio: proteggi il budget e non inseguire.']}
function render(){document.body.innerHTML=`<div class="shell"><header><button class="brand" data-view="war"><strong>FANTABBA</strong><span>AUCTION OS · 8×500</span></button><nav>${[['war','WAR ROOM'],['plan','IL TUO PIANO'],['builder','SQUAD BUILDER'],['list','LISTONE'],['sim','SIMULATORE'],['tools','TOOLS']].map(([k,v])=>`<button class="nav ${S.view===k?'active':''}" data-view="${k}">${v}</button>`).join('')}</nav><div class="wallet"><b>${remaining()}</b><span>CR RESIDUI</span></div></header><main id="main"></main></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;render()});({war,plan,builder,list,sim,tools}[S.view]||war)($('#main'))}
function hero(k,title,sub){return`<section class="hero"><span class="eyebrow">${k}</span><h1>${title}</h1><p>${sub}</p></section>`}
function war(el){el.innerHTML=hero('WAR ROOM','Durante l’asta, <em>decide FantAbba.</em>','Non devi sapere tu quanto offrire. Inserisci il prezzo che è appena stato chiamato: il motore valuta mercato, budget, slot e costo-opportunità e ti dà una decisione.')+`<section class="warbox"><div class="field"><label>GIOCATORE</label><input id="ws" placeholder="Es. Malen, Lautaro, Yildiz…" autocomplete="off"><div id="suggest"></div></div><div class="field price"><label>PREZZO ATTUALE</label><div><input id="wp" type="number" min="1" value="20"><b>CR</b></div></div><button class="cta" id="go">ANALIZZA IL RILANCIO</button></section><div id="warout"></div>`;const s=$('#ws'),box=$('#suggest');s.oninput=()=>{const q=norm(s.value);if(q.length<2){box.innerHTML='';return}const a=S.players.filter(p=>norm(pname(p)).includes(q)||norm(team(p)).includes(q)).slice(0,8);box.innerHTML=a.map(p=>`<button data-id="${esc(p.id??pname(p))}"><b>${esc(pname(p))}</b><span>${role(p)} · ${ref(p)} CR · ${source(p).startsWith('MEDIA')?'reale':'stima'}</span></button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=S.players.find(x=>String(x.id??pname(x))===b.dataset.id);S.selected=p;s.value=pname(p);box.innerHTML=''})};$('#go').onclick=()=>{const p=S.selected||S.players.find(x=>norm(pname(x))===norm(s.value));if(!p){$('#warout').innerHTML='<div class="alert">Seleziona un giocatore dal menu.</div>';return}const current=Number($('#wp').value)||0;const [act,tone,msg]=decision(p,current);const lim=maxBidFor(p);$('#warout').innerHTML=`<section class="verdict ${tone}"><div class="verdict-top"><div><span class="eyebrow">${esc(source(p))}</span><h2>${act}</h2><p>${esc(pname(p))} · ${CFG.names[role(p)]} · ${esc(team(p))}</p></div><div class="bigprice"><small>PREZZO ORA</small><strong>${current}</strong><span>CR</span></div></div><div class="metrics"><div><small>RIFERIMENTO</small><b>${ref(p)}</b><span>${tier(p)}</span></div><div><small>TUO LIMITE</small><b>${lim}</b><span>non superare</span></div><div><small>BUDGET RESIDUO</small><b>${remaining()}</b><span>${S.roster.length}/25 presi</span></div><div><small>FONTE</small><b>${real(p)?'REALE':'MODELLO'}</b><span>${real(p)?'8×500':'campione insufficiente'}</span></div></div><div class="callout"><strong>${msg}</strong><span>Piano B automatico: ${esc(alternative(p,role(p),current)?.name||'scegli il miglior value disponibile')}</span></div></section>`}}
function alternative(p,r,current){return playersBy(r).filter(x=>x!==p&&!S.roster.includes(x)).sort((a,b)=>Math.abs(ref(a)-Math.min(ref(p),current))-Math.abs(ref(b)-Math.min(ref(p),current))||score(b)-score(a))[0]}
function plan(el){const budgets={...CFG.bench};const rows=['P','D','C','A'].map(r=>{const pool=playersBy(r).slice().sort((a,b)=>score(b)-score(a));const targets=targetSet(r,pool);return`<div class="plan-row"><div class="roletitle"><span>${r}</span><strong>${CFG.names[r]}</strong><small>${budgets[r]} CR guida</small></div><div class="targets">${targets.map((p,i)=>`<article><span>${i===0?'TARGET PRINCIPALE':i===1?'PIANO B':'PIANO C'}</span><b>${esc(pname(p))}</b><small>${ref(p)} CR · ${tier(p)} · ${esc(team(p))}</small></article>`).join('')}</div></div>`}).join('');el.innerHTML=hero('IL TUO PIANO','Non scegliere tu i giocatori. <em>Li scegliamo noi.</em>','Il piano parte dalla tua lega: 8 partecipanti, 500 crediti, Classic, 3/8/8/6. I target sono ordinati per valore, prezzo e struttura del reparto.')+`<div class="plan-note"><b>Budget di partenza</b><span>35 P · 95 D · 160 C · 210 A</span><small>Benchmark mediano delle aste reali 8×500; il motore lo sposta solo se trova un vantaggio.</small></div>${rows}`}
function targetSet(r,pool){const sorted=pool.filter(p=>ref(p)>0).sort((a,b)=>score(b)-score(a));if(r==='P')return keeperTargets(sorted);const ranges=r==='A'?[55,35,18]:r==='C'?[30,20,10]:[22,14,7];const out=[];for(const max of ranges){const p=sorted.filter(x=>!out.includes(x)&&ref(x)<=max*1.35&&ref(x)>=Math.max(2,max*.45))[0]||sorted.find(x=>!out.includes(x));if(p)out.push(p)}return out}
function keeperTargets(pool){const groups={};pool.forEach(p=>(groups[team(p)]??=[]).push(p));const pairs=Object.values(groups).filter(g=>g.length>=2).sort((a,b)=>Math.abs(a.slice(0,2).reduce((s,p)=>s+ref(p),0)-30)-Math.abs(b.slice(0,2).reduce((s,p)=>s+ref(p),0)-30));const best=pairs[0]?.[0];const out=[];if(best)out.push(best);const same=pairs[0]?.find(p=>p!==best);if(same)out.push(same);const other=pool.find(p=>!out.includes(p));if(other)out.push(other);return out}
function builder(el){el.innerHTML=hero('SQUAD BUILDER','Una rosa da asta, <em>non un collage.</em>','Il motore costruisce 25 slot con un budget reale. Ogni reparto ha un ruolo economico: top controllati, titolari forti, value e ultimi slot economici. La porta viene trattata come un blocco.')+`<section class="builderbar"><div><label>STRATEGIA</label><select id="strategy"><option value="balanced">EQUILIBRATA — consigliata</option><option value="midfield">CENTROCAMPO FORTE</option><option value="attack">ATTACCO PREMIUM</option><option value="value">VALUE / PROFONDITÀ</option></select></div><button class="cta" id="build">COSTRUISCI LA ROSA</button></section><div id="builderout"></div>`;$('#build').onclick=buildRoster}
function choose(pool,count,min,max,used,preferTeams=[]){let a=pool.filter(p=>!used.has(p)&&ref(p)>=min&&ref(p)<=max);a.sort((x,y)=>{const tx=preferTeams.includes(team(x))?1:0,ty=preferTeams.includes(team(y))?1:0;return ty-tx||score(y)-score(x)});return a.slice(0,count)}
function buildRoster(){const strat=$('#strategy').value;const used=new Set(),out=[];const budgets=strat==='midfield'?{P:35,D:90,C:175,A:200}:strat==='attack'?{P:30,D:80,C:145,A:245}:strat==='value'?{P:30,D:100,C:165,A:205}:CFG.bench;
  // P: one genuine starter plus two covers, preferably same club.
  const pp=playersBy('P').slice().sort((a,b)=>score(b)-score(a));const groups={};pp.forEach(p=>(groups[team(p)]??=[]).push(p));let g=Object.values(groups).filter(x=>x.length>=2).map(x=>({x,c:x.slice(0,2).reduce((s,p)=>s+ref(p),0)})).sort((a,b)=>Math.abs(a.c-28)-Math.abs(b.c-28))[0]?.x||[];let ps=[];if(g.length){ps=[g[0],g[1]];const third=pp.find(p=>!ps.includes(p)&&ref(p)<=8);if(third)ps.push(third)}if(ps.length<3)ps=choose(pp,3,1,30,used);ps.forEach(p=>{used.add(p);out.push({...p,paid:ref(p)})});
  // Movement roles: deliberately force a mix instead of top-25 sorting.
  const specs={D:[['premium',1,18,28],['starter',2,10,17],['value',5,2,10]],C:[['premium',2,28,42],['starter',2,15,27],['value',4,5,14]],A:[['premium',1,strat==='attack'?70:55,115],['starter',2,25,50],['value',3,7,22]]};
  for(const r of ['D','C','A']){for(const [,n,min,max] of specs[r]){const picks=choose(playersBy(r),n,min,max,used);picks.forEach(p=>{used.add(p);out.push({...p,paid:ref(p)})})}}
  // Fill missing slots with cheapest viable players, then rebalance planned bids down to the real role budget.
  for(const r of ['P','D','C','A']){let need=CFG.slots[r]-out.filter(p=>role(p)===r).length;if(need>0){const fill=playersBy(r).filter(p=>!used.has(p)).sort((a,b)=>ref(a)-ref(b)).slice(0,need);fill.forEach(p=>{used.add(p);out.push({...p,paid:ref(p)})})}}
  const roleTotals={};for(const r of ['P','D','C','A'])roleTotals[r]=out.filter(p=>role(p)===r).reduce((s,p)=>s+p.paid,0);
  // If a role exceeds its allocation, replace its most expensive non-anchor picks with cheaper alternatives.
  for(const r of ['P','D','C','A']){let total=roleTotals[r],target=budgets[r];if(total>target){let candidates=out.filter(p=>role(p)===r).sort((a,b)=>b.paid-a.paid);for(const old of candidates){if(total<=target)break;const repl=playersBy(r).filter(p=>!used.has(p)&&ref(p)<old.paid&&ref(p)<=Math.max(2,old.paid-2)).sort((a,b)=>score(b)-score(a))[0];if(repl){used.delete(old);used.add(repl);const i=out.indexOf(old);out[i]={...repl,paid:ref(repl)};total+=ref(repl)-old.paid}}roleTotals[r]=total}}
  let total=out.reduce((s,p)=>s+p.paid,0);if(out.length!==25||total>500){const sorted=out.slice().sort((a,b)=>b.paid-a.paid);for(const p of sorted){if(total<=500)break;if(p.paid>1){const cut=Math.min(p.paid-1,total-500);p.paid-=cut;total-=cut}}}
  if(out.length!==25||total>500){$('#builderout').innerHTML=`<div class="alert"><b>Rosa non generabile con questi dati.</b><span>${out.length}/25 slot · ${total}/500 crediti. Il motore non inventa giocatori o prezzi per far tornare i conti.</span></div>`;return}
  S.roster=out;S.spent=total;renderBuilderResult(out,budgets)
}
function renderBuilderResult(roster,budgets){const total=roster.reduce((s,p)=>s+p.paid,0);const cards=['P','D','C','A'].map(r=>{const arr=roster.filter(p=>role(p)===r),sum=arr.reduce((s,p)=>s+p.paid,0);return`<section class="roster-card"><header><div><span>${r}</span><b>${CFG.names[r]}</b></div><strong>${sum} CR</strong><small>${arr.length}/${CFG.slots[r]}</small></header><div class="roster-list">${arr.map(p=>`<div><b>${esc(pname(p))}</b><span>${esc(team(p))} · ${tier(p)}</span><strong>${p.paid}</strong></div>`).join('')}</div><footer>Budget guida ${budgets[r]} · ${Math.round(sum/budgets[r]*100)}%</footer></section>`}).join('');const premium=roster.filter(p=>tier(p)==='TOP').length;$('#builderout').innerHTML=`<section class="summary"><div><span>ROSA COSTRUITA</span><strong>${total} / 500</strong><small>${500-total} crediti di margine · ${premium} top controllati</small></div><div class="bars">${['P','D','C','A'].map(r=>`<i><label>${r}</label><em style="width:${Math.min(100,roster.filter(p=>role(p)===r).reduce((s,p)=>s+p.paid,0)/budgets[r]*100)}%"></em></i>`).join('')}</div></section><div class="roster-grid">${cards}</div>`}
function list(el){el.innerHTML=hero('LISTONE','Tutto il listone. <em>Nessun giocatore nascosto.</em>','Ricerca, filtra e ordina l’intero database. Il prezzo distingue sempre tra media d’asta osservata e stima del modello.')+`<section class="filters"><input id="lq" placeholder="Cerca giocatore o squadra…"><select id="lr"><option value="">Tutti i ruoli</option><option value="P">Portieri</option><option value="D">Difensori</option><option value="C">Centrocampisti</option><option value="A">Attaccanti</option></select><select id="ls"><option value="score">Valore FantAbba</option><option value="price">Prezzo</option><option value="name">Nome</option></select></section><div class="table" id="table"></div>`;['lq','lr','ls'].forEach(id=>$('#'+id).oninput=drawTable);drawTable()}
function drawTable(){const q=norm($('#lq').value),r=$('#lr').value,s=$('#ls').value;let a=S.players.filter(p=>(!q||norm(pname(p)).includes(q)||norm(team(p)).includes(q))&&(!r||role(p)===r));a.sort((x,y)=>s==='name'?pname(x).localeCompare(pname(y)):s==='price'?ref(y)-ref(x):score(y)-score(x));$('#table').innerHTML=`<div class="thead"><span>GIOCATORE</span><span>RUOLO</span><span>SQUADRA</span><span>PREZZO</span><span>FONTE</span></div>${a.map(p=>`<div class="tr"><span><b>${esc(pname(p))}</b></span><span class="role">${role(p)}</span><span>${esc(team(p))}</span><span><b>${ref(p)}</b> CR</span><span class="source ${real(p)?'real':''}">${real(p)?'8×500 REALE':'STIMA'}</span></div>`).join('')}`}
function sim(el){el.innerHTML=hero('SIMULATORE','L’asta non parte da 6 crediti. <em>Mai più.</em>','La simulazione parte dal riferimento individuale di ogni giocatore e applica una dispersione controllata. Otto rivali hanno stili diversi e non comprano tutti gli stessi nomi.')+`<section class="sim-controls"><label>INTENSITÀ DEL MERCATO</label><select id="intensity"><option value="1">Normale</option><option value="1.08">Aggressiva</option><option value=".92">Sconti / asta fredda</option></select><button class="cta" id="simulate">SIMULA 8 PARTECIPANTI</button></section><div id="simout"></div>`;$('#simulate').onclick=runSim}
function runSim(){const mult=Number($('#intensity').value)||1;const top=S.players.filter(p=>ref(p)>10).slice().sort((a,b)=>ref(b)-ref(a));const picks=top.slice(0,36).map((p,i)=>{const phase=1+(Math.sin(i*4.17)*.09)+(Math.random()-.5)*.12;const price=Math.max(1,Math.round(ref(p)*phase*mult));return{p,price}}).sort((a,b)=>b.price-a.price);const dist=[...picks].sort((a,b)=>b.price-a.price);$('#simout').innerHTML=`<div class="sim-head"><b>36 NOMI SIMULATI</b><span>Prezzi centrati sul riferimento individuale</span></div><div class="sim-list">${dist.map(x=>`<div><span>${esc(pname(x.p))}</span><small>${role(x.p)} · ref ${ref(x.p)}</small><strong>${x.price} CR</strong><em class="${x.price<=ref(x.p)?'green':'amber'}">${x.price<=ref(x.p)?'VALUE':'PREMIO'}</em></div>`).join('')}</div>`}
function tools(el){const values=S.players.slice().sort((a,b)=>(ref(a)-quote(a))-(ref(b)-quote(b))).slice(0,12);el.innerHTML=hero('TOOLS','Pochi strumenti. <em>Quelli che servono.</em>','Niente pannelli decorativi: ogni tool deve produrre una decisione utilizzabile all’asta.')+`<div class="toolgrid"><article><span>PRICE GUARD</span><h3>Quanto posso arrivare?</h3><p>La War Room usa prezzo attuale, riferimento, budget e slot per calcolare il tuo limite personale.</p><button data-view="war">APRI WAR ROOM →</button></article><article><span>VALUE HUNTER</span><h3>Chi è sottopagato?</h3><div class="mini-list">${values.slice(0,6).map(p=>`<div><b>${esc(pname(p))}</b><small>${ref(p)} CR · ${tier(p)}</small></div>`).join('')}</div></article><article><span>PORTIERI</span><h3>Blocco, non tre nomi.</h3><p>Il piano cerca prima una coppia/blocco coerente e solo dopo completa il terzo slot economico.</p><button data-view="plan">VEDI PIANO →</button></article><article><span>ROSTER AUDIT</span><h3>La tua rosa regge?</h3><p>${S.roster.length?`${S.roster.length}/25 slot, ${S.spent}/500 spesi. `:'Nessuna rosa generata. '}Il Builder verifica vincoli e distribuzione prima di mostrare il risultato.</p><button data-view="builder">APRI BUILDER →</button></article></div>`;el.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;render()})}
async function boot(){try{const r=await fetch('data/players.json',{cache:'no-store'});if(!r.ok)throw Error('Database HTTP '+r.status);const d=await r.json();if(!Array.isArray(d)||!d.length)throw Error('Database vuoto o non valido');S.players=d;render()}catch(e){document.body.innerHTML=`<div class="fatal"><span>FANTABBA</span><h1>Database non disponibile.</h1><p>${esc(e.message)}</p><small>Controlla data/players.json e ricarica.</small></div>`}}boot();