/* FantAbba V10 — Auction Intelligence Engine
   8 teams / 500 credits / Classic 3-8-8-6 by default.
   Data hierarchy: observed auction price > external benchmark > model estimate.
*/
(() => {
  'use strict';
  const CFG={budget:500, slots:{P:3,D:8,C:8,A:6}, minBudgetPerSlot:1};
  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const role=r=>{r=String(r||'').toUpperCase(); if(r.includes('PORT'))return'P'; if(r.includes('DIF'))return'D'; if(r.includes('CEN')||r==='M'||r.includes('TREQ')||r.includes('COM'))return'C'; return'A'};
  const money=n=>`${Math.round(Number(n)||0)} cr`;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const tier=v=>v>=.82?'ELITE':v>=.68?'PREMIUM':v>=.52?'SOLID':v>=.35?'VALUE':'DEPTH';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let players=[],state={budget:500,roster:{P:[],D:[],C:[],A:[]},current:null};
  const priceOf=p=>{let x=Number(p.auctionAvg8x500??p.avg8x500??p.price8x500??p.auctionPrice); return Number.isFinite(x)&&x>0?{value:x,source:'MEDIA 8×500'}:null};
  function estimate(p){const q=Number(p.q||p.quotazione||p.quote||p.price||1); const r=role(p.role||p.classicRole||p.position); const base={P:1.7,D:2.6,C:3.5,A:4.0}[r]; const f=Number(p.fvm||p.fvm1000||p.fvmScore||0); const raw=q*base*(1+clamp(f/1000,0,.35)*.45); const caps={P:35,D:65,C:90,A:140}; return clamp(Math.round(raw),1,caps[r]);}
  const ref=p=>priceOf(p)||{value:estimate(p),source:'STIMA MODELLO'};
  function quality(p){const q=Number(p.q||p.quotazione||p.quote||1), f=Number(p.fvm||p.fvm1000||0); return clamp((q/35)*.58+(f/400)*.42,0,1)}
  function budgetPlan(){return {P:35,D:95,C:160,A:210};}
  function rosterCost(){return Object.values(state.roster).flat().reduce((s,p)=>s+ref(p).value,0)}
  function remainingSlots(){return Object.fromEntries(Object.entries(CFG.slots).map(([r,n])=>[r,n-state.roster[r].length]));}
  function feasibleAfter(r,cost){const rem=remainingSlots(); rem[r]--; const spent=rosterCost()+cost; const slots=Object.values(rem).reduce((a,b)=>a+b,0); return spent+slots<=CFG.budget;}
  function decide(p,current){const refv=ref(p).value, cur=Number(current)||0; const rem=remainingSlots(); const mustKeep=Object.values(rem).reduce((a,b)=>a+b,0)-1; const reserve=Math.max(mustKeep,0); const maxByBudget=CFG.budget-rosterCost()-reserve; const max=clamp(Math.round(Math.min(refv*1.10,maxByBudget)),1,500); const ratio=cur/refv; let action='STOP',tone='bad'; if(cur<=refv*.72){action='RILANCIA FORTE';tone='good'} else if(cur<=refv*.88){action='RILANCIA';tone='good'} else if(cur<=refv*.98){action='RILANCIA';tone='warn'} else if(cur<=max){action='ULTIMO RILANCIO';tone='warn'} return {ref:refv,source:ref(p).source,max,action,tone,ratio};}
  function build(){const out={P:[],D:[],C:[],A:[]}; const budgets=budgetPlan(); let spent=0; for(const r of ['P','D','C','A']){let need=CFG.slots[r], target=budgets[r]; const pool=players.filter(p=>role(p.role||p.classicRole||p.position)===r).map(p=>({...p,_r:ref(p).value,_q:quality(p)})).filter(p=>p._r+1<=target||need>0); pool.sort((a,b)=>((b._q/(b._r+1))-(a._q/(a._r+1)))); const chosen=[]; let remBudget=target; while(chosen.length<need&&pool.length){let best=pool.findIndex(p=>p._r<=remBudget-(need-chosen.length-1)); if(best<0)best=pool.length-1; const p=pool.splice(best,1)[0]; chosen.push(p); remBudget-=p._r; spent+=p._r;} out[r]=chosen;} const total=Object.values(out).flat().reduce((s,p)=>s+ref(p).value,0); return {out,total,valid:Object.values(out).every((a,i)=>a.length===[3,8,8,6][i])&&total<=CFG.budget};}
  function find(q){const n=norm(q); return players.filter(p=>norm(p.name||p.fullName||p.playerName).includes(n)).slice(0,20);}
  function render(){const root=document.getElementById('app'); if(!root)return; root.innerHTML=`<div class="fb-shell"><header><div><span class="brand">FANTABBA</span><span class="sub">AUCTION INTELLIGENCE</span></div><div class="budget">${money(state.budget)} <small>residui</small></div></header><nav><button data-tab="war">WAR ROOM</button><button data-tab="build">SQUAD BUILDER</button><button data-tab="list">LISTONE</button><button data-tab="tools">TOOLS</button></nav><main id="view"></main></div>`; view('war'); document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.tab));}
  function view(tab){const v=document.getElementById('view'); if(!v)return; if(tab==='war')v.innerHTML=`<section class="hero"><div><div class="eyebrow">LIVE AUCTION</div><h1>Dimmi il prezzo.<br><em>Ti dico cosa fare.</em></h1><p>Inserisci un giocatore e il prezzo attuale. FantAbba calcola valore, limite e costo-opportunità sulla tua rosa.</p></div><div class="war-card"><input id="search" placeholder="Cerca giocatore…"><div id="matches"></div><input id="cur" type="number" min="1" placeholder="Prezzo attuale dell'asta"><button id="analyse">ANALIZZA</button><div id="verdict"></div></div></section>`;
    else if(tab==='build')v.innerHTML=`<section><div class="eyebrow">OPTIMIZER</div><h2>La rosa non si sceglie. Si ottimizza.</h2><p>Vincoli: 3 P · 8 D · 8 C · 6 A · massimo 500. Budget guida 35/95/160/210, ma il motore può spostarlo quando il valore marginale lo giustifica.</p><button id="generate">GENERA ROSA OTTIMALE</button><div id="rose"></div></section>`;
    else if(tab==='list')v.innerHTML=`<section><div class="eyebrow">DATABASE</div><h2>Listone completo</h2><input id="listq" placeholder="Cerca…"><select id="rolef"><option value="">Tutti i ruoli</option><option>P</option><option>D</option><option>C</option><option>A</option></select><div id="table"></div></section>`;
    else v.innerHTML=`<section><div class="eyebrow">DECISION TOOLS</div><h2>Strumenti che prendono decisioni.</h2><div class="grid"><article><b>PRICE GUARD</b><p>Confronta prezzo corrente e valore di mercato.</p></article><article><b>SCARCITY</b><p>Misura quante alternative rimangono per ruolo e fascia.</p></article><article><b>BUDGET GUARD</b><p>Protegge i crediti necessari per completare la rosa.</p></article><article><b>PORTIERI</b><p>Non compra tre top: valuta blocco, costo e incrocio.</p></article></div></section>`;
    bind(tab);
  }
  function bind(tab){if(tab==='war'){const s=document.getElementById('search'),m=document.getElementById('matches'); s.oninput=()=>{m.innerHTML=find(s.value).map((p,i)=>`<button class="match" data-i="${i}">${esc(p.name||p.fullName)} <span>${role(p.role||p.classicRole||p.position)}</span></button>`).join('');m.querySelectorAll('.match').forEach(b=>b.onclick=()=>{state.current=find(s.value)[+b.dataset.i];s.value=state.current.name||state.current.fullName;m.innerHTML='';});}; document.getElementById('analyse').onclick=()=>{if(!state.current)return;const d=decide(state.current,document.getElementById('cur').value);document.getElementById('verdict').innerHTML=`<div class="decision ${d.tone}"><strong>${d.action}</strong><div>Riferimento: <b>${money(d.ref)}</b> · Attuale: <b>${money(document.getElementById('cur').value)}</b></div><div>Limite assoluto: <b>${money(d.max)}</b></div><small>${d.source}</small></div>`;};}
    if(tab==='build')document.getElementById('generate').onclick=()=>{try{const b=build();document.getElementById('rose').innerHTML=b.out?Object.entries(b.out).map(([r,a])=>`<div class="rep"><h3>${r} <small>${a.length}/${CFG.slots[r]}</small></h3>${a.map(p=>`<div>${esc(p.name||p.fullName)} <b>${money(ref(p).value)}</b></div>`).join('')}</div>`).join('')+`<div class="total">TOTALE <b>${money(b.total)}</b> · ${b.valid?'VALIDA':'NON VALIDA'}</div>`:'Errore';}catch(e){document.getElementById('rose').innerHTML='<div class="error">Impossibile costruire una rosa valida con i dati attuali.</div>';console.error(e);}};
    if(tab==='list'){const draw=()=>{const q=norm(document.getElementById('listq').value),rf=document.getElementById('rolef').value;const arr=players.filter(p=>(!q||norm(p.name||p.fullName).includes(q))&&(!rf||role(p.role||p.classicRole||p.position)===rf));document.getElementById('table').innerHTML=`<table><thead><tr><th>Giocatore</th><th>Ruolo</th><th>Q</th><th>Prezzo</th><th>Fonte</th></tr></thead><tbody>${arr.map(p=>{const r=ref(p);return`<tr><td>${esc(p.name||p.fullName)}</td><td>${role(p.role||p.classicRole||p.position)}</td><td>${p.q??p.quotazione??'-'}</td><td>${money(r.value)}</td><td>${r.source}</td></tr>`}).join('')}</tbody></table>`}; document.getElementById('listq').oninput=draw;document.getElementById('rolef').onchange=draw;draw();}}
  async function boot(){try{const res=await fetch('data/players.json',{cache:'no-store'});players=await res.json();if(!Array.isArray(players))throw Error('database');render();}catch(e){document.body.innerHTML='<div class="fatal">FantAbba non riesce a caricare il database giocatori. Riprova tra poco.</div>';console.error(e);}}
  boot();
})();